// Top ~1000 most famous paintings, curated by hand.
// Each entry has:
//   name:      local filename
//   wikimedia: exact Wikimedia Commons filename (tried first, optional)
//   search:    search query for Commons API fallback (optional)
// download-references.js tries wikimedia first, then search, skips failures.
//
// Organized roughly by art-historical period / artist.

module.exports = [
  // =====================================================================
  // MEDIEVAL & PROTO-RENAISSANCE
  // =====================================================================
  { name: "kiss-of-judas-giotto.jpg", search: "Kiss of Judas Giotto Scrovegni" },
  { name: "lamentation-giotto.jpg", search: "Lamentation Giotto Scrovegni" },
  { name: "ognissanti-madonna-giotto.jpg", search: "Ognissanti Madonna Giotto" },
  { name: "stigmata-st-francis-giotto.jpg", search: "Stigmatization Saint Francis Giotto" },
  { name: "flight-into-egypt-giotto.jpg", search: "Flight into Egypt Giotto Scrovegni" },
  { name: "annunciation-fra-angelico.jpg", search: "Annunciation Fra Angelico" },
  { name: "expulsion-masaccio.jpg", search: "Expulsion Garden Eden Masaccio" },
  { name: "tribute-money-masaccio.jpg", search: "Tribute Money Masaccio Brancacci" },
  { name: "holy-trinity-masaccio.jpg", search: "Holy Trinity Masaccio Santa Maria Novella" },
  { name: "adoration-magi-gentile.jpg", search: "Adoration Magi Gentile da Fabriano" },
  { name: "maesta-duccio.jpg", search: "Maestà Duccio Siena" },
  { name: "allegory-good-government-lorenzetti.jpg", search: "Allegory Good Government Lorenzetti Siena" },
  { name: "wilton-diptych.jpg", search: "Wilton Diptych Richard II" },

  // =====================================================================
  // EARLY & NORTHERN RENAISSANCE
  // =====================================================================
  { name: "arnolfini-portrait.jpg", wikimedia: "Van_Eyck_-_Arnolfini_Portrait.jpg", search: "Arnolfini Portrait Van Eyck" },
  { name: "ghent-altarpiece.jpg", search: "Ghent Altarpiece Adoration Mystic Lamb Van Eyck" },
  { name: "man-in-red-turban.jpg", search: "Man Red Turban Jan van Eyck self portrait" },
  { name: "madonna-chancellor-rolin.jpg", search: "Madonna Chancellor Rolin Van Eyck" },
  { name: "descent-cross-weyden.jpg", search: "Descent Cross Rogier van der Weyden" },
  { name: "portrait-lady-weyden.jpg", search: "Portrait Lady Rogier van der Weyden National Gallery" },
  { name: "garden-of-earthly-delights.jpg", wikimedia: "The_Garden_of_earthly_delights.jpg", search: "Garden Earthly Delights Bosch" },
  { name: "haywain-triptych-bosch.jpg", search: "Haywain Triptych Bosch Prado" },
  { name: "last-judgment-bosch.jpg", search: "Last Judgment Bosch triptych" },
  { name: "temptation-st-anthony-bosch.jpg", search: "Temptation Saint Anthony Bosch" },
  { name: "ship-of-fools-bosch.jpg", search: "Ship of Fools Bosch" },
  { name: "tower-of-babel.jpg", wikimedia: "Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_(Vienna)_-_Google_Art_Project_-_edited.jpg", search: "Tower Babel Bruegel Vienna" },
  { name: "hunters-in-the-snow.jpg", wikimedia: "Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_(Winter)_-_Google_Art_Project.jpg", search: "Hunters Snow Bruegel" },
  { name: "fall-of-icarus.jpg", search: "Landscape Fall Icarus Bruegel" },
  { name: "peasant-wedding-bruegel.jpg", search: "Peasant Wedding Bruegel" },
  { name: "netherlandish-proverbs-bruegel.jpg", search: "Netherlandish Proverbs Bruegel" },
  { name: "harvesters-bruegel.jpg", search: "Harvesters Bruegel Metropolitan" },
  { name: "triumph-death-bruegel.jpg", search: "Triumph Death Bruegel Prado" },
  { name: "ambassadors.jpg", wikimedia: "Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg", search: "Ambassadors Holbein National Gallery" },
  { name: "henry-viii-holbein.jpg", search: "Henry VIII portrait Holbein" },
  { name: "self-portrait-durer-1500.jpg", search: "Self Portrait Albrecht Dürer 1500 Munich" },
  { name: "melencolia-durer.jpg", search: "Melencolia Dürer engraving" },
  { name: "young-hare-durer.jpg", search: "Young Hare Dürer Albertina" },
  { name: "adam-eve-durer.jpg", search: "Adam Eve Dürer Prado" },
  { name: "four-apostles-durer.jpg", search: "Four Apostles Dürer Munich" },
  { name: "memling-last-judgment.jpg", search: "Last Judgment Hans Memling Gdańsk" },
  { name: "portinari-altarpiece.jpg", search: "Portinari Altarpiece Hugo van der Goes" },

  // =====================================================================
  // ITALIAN HIGH RENAISSANCE
  // =====================================================================
  // Leonardo da Vinci
  { name: "mona-lisa.jpg", wikimedia: "Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg", search: "Mona Lisa Leonardo da Vinci" },
  { name: "last-supper.jpg", search: "Last Supper Leonardo da Vinci Milan" },
  { name: "lady-with-ermine.jpg", search: "Lady with an Ermine Leonardo da Vinci" },
  { name: "virgin-of-the-rocks.jpg", search: "Virgin Rocks Leonardo Louvre" },
  { name: "annunciation-leonardo.jpg", search: "Annunciation Leonardo da Vinci Uffizi" },
  { name: "virgin-child-st-anne.jpg", search: "Virgin Child Saint Anne Leonardo Louvre" },
  { name: "ginevra-de-benci.jpg", search: "Ginevra de Benci Leonardo Washington" },
  { name: "salvator-mundi-leonardo.jpg", search: "Salvator Mundi Leonardo da Vinci" },
  // Botticelli
  { name: "birth-of-venus.jpg", wikimedia: "Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg", search: "Birth Venus Botticelli" },
  { name: "primavera.jpg", search: "Primavera Botticelli Uffizi" },
  { name: "adoration-magi-botticelli.jpg", search: "Adoration Magi Botticelli Uffizi" },
  { name: "venus-mars-botticelli.jpg", search: "Venus Mars Botticelli National Gallery" },
  { name: "map-of-hell-botticelli.jpg", search: "Map Hell Botticelli Divine Comedy" },
  // Michelangelo
  { name: "creation-of-adam.jpg", wikimedia: "Michelangelo_-_Creation_of_Adam_(cropped).jpg", search: "Creation Adam Michelangelo Sistine" },
  { name: "last-judgment-michelangelo.jpg", search: "Last Judgment Michelangelo Sistine Chapel" },
  { name: "delphic-sibyl-michelangelo.jpg", search: "Delphic Sibyl Michelangelo Sistine ceiling" },
  { name: "creation-of-eve-michelangelo.jpg", search: "Creation Eve Michelangelo Sistine" },
  { name: "doni-tondo-michelangelo.jpg", search: "Doni Tondo Holy Family Michelangelo" },
  // Raphael
  { name: "school-of-athens.jpg", search: "School Athens Raphael Vatican" },
  { name: "transfiguration-raphael.jpg", search: "Transfiguration Raphael Vatican" },
  { name: "sistine-madonna.jpg", search: "Sistine Madonna Raphael Dresden" },
  { name: "madonna-of-the-goldfinch.jpg", search: "Madonna Goldfinch Raphael Uffizi" },
  { name: "portrait-baldassare-castiglione.jpg", search: "Portrait Baldassare Castiglione Raphael Louvre" },
  { name: "galatea-raphael.jpg", search: "Triumph Galatea Raphael" },
  { name: "marriage-of-the-virgin-raphael.jpg", search: "Marriage Virgin Raphael Brera" },
  // Titian
  { name: "venus-of-urbino.jpg", wikimedia: "Tiziano_-_Venere_di_Urbino_-_Google_Art_Project.jpg", search: "Venus Urbino Titian" },
  { name: "assumption-virgin-titian.jpg", search: "Assumption Virgin Titian Frari Venice" },
  { name: "bacchus-and-ariadne.jpg", search: "Bacchus Ariadne Titian National Gallery" },
  { name: "sacred-profane-love-titian.jpg", search: "Sacred Profane Love Titian Borghese" },
  { name: "man-with-glove-titian.jpg", search: "Man Glove Titian Louvre" },
  { name: "diana-actaeon-titian.jpg", search: "Diana Actaeon Titian" },
  { name: "rape-of-europa-titian.jpg", search: "Rape Europa Titian" },
  // Others
  { name: "tempest-giorgione.jpg", search: "Tempest Giorgione Venice" },
  { name: "sleeping-venus-giorgione.jpg", search: "Sleeping Venus Giorgione Dresden" },
  { name: "st-george-dragon-uccello.jpg", search: "Saint George Dragon Paolo Uccello" },
  { name: "battle-san-romano-uccello.jpg", search: "Battle San Romano Uccello" },
  { name: "flagellation-piero-della-francesca.jpg", search: "Flagellation Christ Piero della Francesca" },
  { name: "dream-of-constantine-piero.jpg", search: "Legend True Cross Piero della Francesca Arezzo" },
  { name: "madonna-with-long-neck-parmigianino.jpg", search: "Madonna Long Neck Parmigianino" },
  { name: "wedding-at-cana-veronese.jpg", search: "Wedding Feast Cana Veronese Louvre" },
  { name: "st-jerome-ghirlandaio.jpg", search: "Saint Jerome study Ghirlandaio" },
  { name: "portrait-giovanna-tornabuoni.jpg", search: "Giovanna Tornabuoni Ghirlandaio" },

  // =====================================================================
  // MANNERISM
  // =====================================================================
  { name: "burial-of-count-orgaz.jpg", search: "Burial Count Orgaz El Greco" },
  { name: "view-of-toledo.jpg", search: "View Toledo El Greco" },
  { name: "opening-fifth-seal.jpg", search: "Opening Fifth Seal El Greco" },
  { name: "disrobing-of-christ.jpg", search: "Disrobing Christ El Greco Espolio" },
  { name: "laocoon-el-greco.jpg", search: "Laocoön El Greco" },
  { name: "christ-driving-traders-el-greco.jpg", search: "Christ Driving Traders Temple El Greco" },
  { name: "portrait-gentleman-el-greco.jpg", search: "Nobleman Hand Chest El Greco" },
  { name: "descent-holy-spirit-el-greco.jpg", search: "Pentecost El Greco" },
  { name: "self-portrait-pontormo.jpg", search: "Deposition Pontormo" },
  { name: "venus-cupid-folly-bronzino.jpg", search: "Venus Cupid Folly Time Bronzino allegory" },

  // =====================================================================
  // BAROQUE
  // =====================================================================
  // Vermeer
  { name: "girl-with-a-pearl-earring.jpg", wikimedia: "1665_Girl_with_a_Pearl_Earring.jpg", search: "Girl Pearl Earring Vermeer" },
  { name: "the-milkmaid.jpg", search: "Milkmaid Vermeer Rijksmuseum" },
  { name: "view-of-delft.jpg", search: "View Delft Vermeer" },
  { name: "the-lacemaker.jpg", search: "Lacemaker Vermeer" },
  { name: "girl-reading-letter.jpg", search: "Girl Reading Letter Open Window Vermeer" },
  { name: "art-of-painting-vermeer.jpg", search: "Art Painting Vermeer allegory" },
  { name: "girl-red-hat-vermeer.jpg", search: "Girl Red Hat Vermeer" },
  { name: "music-lesson-vermeer.jpg", search: "Music Lesson Vermeer" },
  { name: "astronomer-vermeer.jpg", search: "Astronomer Vermeer" },
  { name: "geographer-vermeer.jpg", search: "Geographer Vermeer" },
  { name: "woman-holding-balance-vermeer.jpg", search: "Woman Holding Balance Vermeer" },
  { name: "love-letter-vermeer.jpg", search: "Love Letter Vermeer" },
  // Rembrandt
  { name: "the-night-watch.jpg", wikimedia: "The_Nightwatch_by_Rembrandt_-_Rijksmuseum.jpg", search: "Night Watch Rembrandt" },
  { name: "anatomy-lesson.jpg", search: "Anatomy Lesson Dr Tulp Rembrandt" },
  { name: "return-prodigal-son.jpg", search: "Return Prodigal Son Rembrandt Hermitage" },
  { name: "self-portrait-rembrandt.jpg", search: "Self Portrait Rembrandt two circles Kenwood" },
  { name: "jewish-bride-rembrandt.jpg", search: "Jewish Bride Rembrandt Rijksmuseum" },
  { name: "storm-sea-galilee-rembrandt.jpg", search: "Storm Sea Galilee Rembrandt" },
  { name: "bathsheba-rembrandt.jpg", search: "Bathsheba Bath Rembrandt Louvre" },
  { name: "syndics-drapers-rembrandt.jpg", search: "Syndics Drapers Guild Rembrandt Staalmeesters" },
  { name: "philosopher-meditation-rembrandt.jpg", search: "Philosopher Meditation Rembrandt" },
  { name: "self-portrait-rembrandt-1659.jpg", search: "Self Portrait Rembrandt 1659 National Gallery" },
  { name: "belshazzars-feast-rembrandt.jpg", search: "Belshazzar Feast Rembrandt" },
  // Caravaggio
  { name: "calling-of-st-matthew.jpg", search: "Calling Saint Matthew Caravaggio" },
  { name: "judith-holofernes-caravaggio.jpg", search: "Judith Beheading Holofernes Caravaggio" },
  { name: "judith-holofernes-artemisia.jpg", search: "Judith Beheading Holofernes Artemisia Gentileschi" },
  { name: "david-goliath-caravaggio.jpg", search: "David Head Goliath Caravaggio Borghese" },
  { name: "supper-at-emmaus-caravaggio.jpg", search: "Supper Emmaus Caravaggio National Gallery London" },
  { name: "bacchus-caravaggio.jpg", search: "Bacchus Caravaggio Uffizi" },
  { name: "narcissus-caravaggio.jpg", search: "Narcissus Caravaggio" },
  { name: "conversion-st-paul-caravaggio.jpg", search: "Conversion Saint Paul Caravaggio" },
  { name: "entombment-caravaggio.jpg", search: "Entombment Christ Caravaggio Vatican" },
  { name: "doubting-thomas-caravaggio.jpg", search: "Incredulity Saint Thomas Caravaggio" },
  { name: "boy-fruit-basket-caravaggio.jpg", search: "Boy Basket Fruit Caravaggio" },
  // Velázquez
  { name: "las-meninas.jpg", wikimedia: "Las_Meninas,_by_Diego_Velázquez,_from_Prado_in_Google_Earth.jpg", search: "Las Meninas Velázquez" },
  { name: "venus-with-mirror-velazquez.jpg", search: "Rokeby Venus Velázquez mirror" },
  { name: "surrender-breda-velazquez.jpg", search: "Surrender Breda Velázquez Lances" },
  { name: "old-woman-frying-eggs-velazquez.jpg", search: "Old Woman Frying Eggs Velázquez" },
  { name: "waterseller-seville-velazquez.jpg", search: "Waterseller Seville Velázquez" },
  { name: "pope-innocent-x-velazquez.jpg", search: "Portrait Pope Innocent X Velázquez Doria" },
  { name: "las-hilanderas-velazquez.jpg", search: "Spinners Fable Arachne Velázquez" },
  // Rubens
  { name: "descent-cross-rubens.jpg", search: "Descent Cross Rubens Antwerp cathedral" },
  { name: "samson-delilah-rubens.jpg", search: "Samson Delilah Rubens National Gallery" },
  { name: "garden-of-love-rubens.jpg", search: "Garden Love Rubens Prado" },
  { name: "elevation-cross-rubens.jpg", search: "Raising Cross Rubens Antwerp" },
  { name: "massacre-innocents-rubens.jpg", search: "Massacre Innocents Rubens" },
  { name: "three-graces-rubens.jpg", search: "Three Graces Rubens Prado" },
  { name: "judgement-paris-rubens.jpg", search: "Judgement Paris Rubens" },
  { name: "tiger-lion-leopard-hunt-rubens.jpg", search: "Tiger Lion Leopard Hunt Rubens" },
  // Others
  { name: "laughing-cavalier-hals.jpg", search: "Laughing Cavalier Frans Hals" },
  { name: "merry-drinker-hals.jpg", search: "Merry Drinker Frans Hals" },
  { name: "gypsy-girl-hals.jpg", search: "Malle Babbe Hals" },
  { name: "girl-with-pearl-earring-style-hals.jpg", search: "Banquet Officers St George Civic Guard Hals" },
  { name: "girl-with-broom-murillo.jpg", search: "Immaculate Conception Murillo" },
  { name: "boy-flea-murillo.jpg", search: "Young Beggar Murillo Louvre" },
  { name: "ecstasy-st-theresa-bernini.jpg", search: "Ecstasy Saint Teresa Bernini" },

  // =====================================================================
  // ROCOCO & 18TH CENTURY
  // =====================================================================
  { name: "the-swing.jpg", wikimedia: "Fragonard,_The_Swing.jpg", search: "Swing Fragonard" },
  { name: "girl-reading-fragonard.jpg", search: "Young Girl Reading Fragonard" },
  { name: "blue-boy-gainsborough.jpg", search: "Blue Boy Gainsborough Huntington" },
  { name: "mr-and-mrs-andrews.jpg", search: "Mr Mrs Andrews Gainsborough" },
  { name: "the-nightmare-fuseli.jpg", search: "Nightmare Fuseli" },
  { name: "pilgrimage-cythera-watteau.jpg", search: "Pilgrimage Cythera Watteau" },
  { name: "pierrot-gilles-watteau.jpg", search: "Pierrot Gilles Watteau Louvre" },
  { name: "fetes-galantes-watteau.jpg", search: "Fêtes galantes Watteau" },
  { name: "odalisque-boucher.jpg", search: "Reclining Girl Boucher Alte Pinakothek" },
  { name: "chardin-still-life.jpg", search: "Still Life Chardin ray" },
  { name: "brioche-chardin.jpg", search: "Brioche Chardin Louvre" },
  { name: "death-general-wolfe-west.jpg", search: "Death General Wolfe Benjamin West" },
  { name: "mrs-siddons-reynolds.jpg", search: "Mrs Siddons Tragic Muse Reynolds" },
  { name: "conversation-piece-hogarth.jpg", search: "Marriage à la Mode Hogarth" },
  { name: "rakes-progress-hogarth.jpg", search: "Rake's Progress Hogarth madhouse" },
  { name: "gin-lane-hogarth.jpg", search: "Gin Lane Hogarth" },
  { name: "caprichos-goya-sleep-reason.jpg", search: "Sleep Reason Produces Monsters Goya Caprichos" },
  { name: "girl-balloon-greuze.jpg", search: "Girl mourns dead bird Greuze" },

  // =====================================================================
  // NEOCLASSICISM
  // =====================================================================
  { name: "oath-of-the-horatii.jpg", search: "Oath Horatii Jacques-Louis David" },
  { name: "napoleon-crossing-alps.jpg", search: "Napoleon Crossing Alps David" },
  { name: "death-of-marat.jpg", search: "Death Marat David" },
  { name: "coronation-of-napoleon.jpg", search: "Coronation Napoleon David Louvre" },
  { name: "intervention-sabine-women.jpg", search: "Intervention Sabine Women David" },
  { name: "death-of-socrates.jpg", search: "Death Socrates David Metropolitan" },
  { name: "grande-odalisque.jpg", search: "Grande Odalisque Ingres" },
  { name: "turkish-bath-ingres.jpg", search: "Turkish Bath Ingres" },
  { name: "source-ingres.jpg", search: "Source Ingres Musée d'Orsay" },
  { name: "valpincon-bather-ingres.jpg", search: "Valpinçon Bather Ingres" },
  { name: "portrait-napoleon-ingres.jpg", search: "Napoleon Throne Ingres" },

  // =====================================================================
  // ROMANTICISM
  // =====================================================================
  // Friedrich
  { name: "wanderer-above-fog.jpg", wikimedia: "Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg", search: "Wanderer Sea Fog Friedrich" },
  { name: "monk-by-the-sea.jpg", search: "Monk Sea Caspar David Friedrich" },
  { name: "chalk-cliffs-rugen.jpg", search: "Chalk Cliffs Rügen Friedrich" },
  { name: "abbey-in-oakwood.jpg", search: "Abbey Oakwood Friedrich" },
  { name: "sea-of-ice-friedrich.jpg", search: "Sea Ice Friedrich Wreck Hope" },
  { name: "two-men-moon-friedrich.jpg", search: "Two Men Contemplating Moon Friedrich" },
  { name: "stages-of-life-friedrich.jpg", search: "Stages Life Friedrich" },
  // Delacroix
  { name: "liberty-leading-people.jpg", search: "Liberty Leading People Delacroix" },
  { name: "death-of-sardanapalus.jpg", search: "Death Sardanapalus Delacroix" },
  { name: "women-of-algiers-delacroix.jpg", search: "Women Algiers Delacroix" },
  { name: "massacre-at-chios-delacroix.jpg", search: "Massacre Chios Delacroix" },
  // Géricault
  { name: "raft-of-the-medusa.jpg", search: "Raft Medusa Géricault" },
  { name: "mad-woman-gericault.jpg", search: "Insane Woman Géricault" },
  // Goya
  { name: "third-of-may.jpg", search: "Third May 1808 Goya executions" },
  { name: "saturn-devouring-son.jpg", search: "Saturn Devouring Son Goya" },
  { name: "maja-desnuda-goya.jpg", search: "Nude Maja Goya" },
  { name: "maja-vestida-goya.jpg", search: "Clothed Maja Goya" },
  { name: "dog-goya.jpg", search: "Dog Goya black paintings" },
  { name: "witches-sabbath-goya.jpg", search: "Witches Sabbath Goya" },
  { name: "charles-iv-family-goya.jpg", search: "Charles IV Family Goya" },
  { name: "colossus-goya.jpg", search: "Colossus Goya" },
  // Turner
  { name: "rain-steam-speed.jpg", search: "Rain Steam Speed Turner" },
  { name: "fighting-temeraire.jpg", search: "Fighting Temeraire Turner" },
  { name: "slave-ship-turner.jpg", search: "Slave Ship Turner" },
  { name: "shipwreck-turner.jpg", search: "Shipwreck Turner" },
  { name: "snow-storm-turner.jpg", search: "Snow Storm Hannibal Turner Alps" },
  { name: "peace-burial-at-sea-turner.jpg", search: "Peace Burial Sea Turner" },
  { name: "sun-rising-through-vapour-turner.jpg", search: "Sun Rising Vapour Turner" },
  // Constable
  { name: "hay-wain.jpg", search: "Hay Wain Constable" },
  { name: "salisbury-cathedral-constable.jpg", search: "Salisbury Cathedral Meadows Constable" },
  { name: "flatford-mill-constable.jpg", search: "Flatford Mill Constable" },
  { name: "dedham-vale-constable.jpg", search: "Dedham Vale Constable" },
  // Others
  { name: "isle-of-dead-bocklin.jpg", search: "Isle Dead Böcklin" },
  { name: "course-empire-cole.jpg", search: "Course Empire Destruction Thomas Cole" },
  { name: "oxbow-cole.jpg", search: "Oxbow Thomas Cole" },
  { name: "heart-of-andes-church.jpg", search: "Heart Andes Frederic Church" },

  // =====================================================================
  // PRE-RAPHAELITES & VICTORIAN
  // =====================================================================
  { name: "ophelia.jpg", wikimedia: "John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg", search: "Ophelia Millais" },
  { name: "lady-of-shalott.jpg", search: "Lady Shalott Waterhouse" },
  { name: "hylas-and-nymphs.jpg", search: "Hylas Nymphs Waterhouse" },
  { name: "miranda-waterhouse.jpg", search: "Miranda Tempest Waterhouse" },
  { name: "circe-waterhouse.jpg", search: "Circe Offering Cup Waterhouse" },
  { name: "beata-beatrix-rossetti.jpg", search: "Beata Beatrix Rossetti" },
  { name: "proserpine-rossetti.jpg", search: "Proserpine Rossetti" },
  { name: "bocca-baciata-rossetti.jpg", search: "Bocca Baciata Rossetti" },
  { name: "golden-stairs-burne-jones.jpg", search: "Golden Stairs Burne-Jones" },
  { name: "love-among-ruins-burne-jones.jpg", search: "Love Among Ruins Burne-Jones" },
  { name: "king-cophetua-beggar-maid-burne-jones.jpg", search: "King Cophetua Beggar Maid Burne-Jones" },
  { name: "flaming-june.jpg", search: "Flaming June Leighton" },
  { name: "christ-house-parents-millais.jpg", search: "Christ House Parents Millais carpenter" },
  { name: "autumn-leaves-millais.jpg", search: "Autumn Leaves Millais" },
  { name: "light-of-world-holman-hunt.jpg", search: "Light World Holman Hunt" },
  { name: "awakening-conscience-hunt.jpg", search: "Awakening Conscience Holman Hunt" },
  { name: "alma-tadema-roses.jpg", search: "Roses Heliogabalus Alma-Tadema" },

  // =====================================================================
  // REALISM
  // =====================================================================
  { name: "the-gleaners.jpg", search: "Gleaners Millet" },
  { name: "the-angelus.jpg", search: "Angelus Millet" },
  { name: "sower-millet.jpg", search: "Sower Millet" },
  { name: "olympia.jpg", search: "Olympia Manet" },
  { name: "dejeuner-sur-lherbe.jpg", search: "Luncheon Grass Manet" },
  { name: "fifer-manet.jpg", search: "Fifer Manet" },
  { name: "execution-maximilian-manet.jpg", search: "Execution Emperor Maximilian Manet" },
  { name: "berthe-morisot-manet.jpg", search: "Berthe Morisot Bouquet Violets Manet" },
  { name: "bar-at-folies.jpg", search: "Bar Folies-Bergère Manet" },
  { name: "whistlers-mother.jpg", search: "Whistler's Mother Arrangement Grey Black" },
  { name: "nocturne-black-gold-whistler.jpg", search: "Nocturne Black Gold Falling Rocket Whistler" },
  { name: "burial-at-ornans.jpg", search: "Burial Ornans Courbet" },
  { name: "painters-studio-courbet.jpg", search: "Painter's Studio Courbet Atelier" },
  { name: "origin-of-world-courbet.jpg", search: "Origin World Courbet" },
  { name: "bonjour-monsieur-courbet.jpg", search: "Bonjour Monsieur Courbet Meeting" },
  { name: "wave-courbet.jpg", search: "Wave Courbet" },
  { name: "stone-breakers-courbet.jpg", search: "Stone Breakers Courbet" },
  { name: "third-class-carriage-daumier.jpg", search: "Third-Class Carriage Daumier" },
  { name: "horse-fair-bonheur.jpg", search: "Horse Fair Rosa Bonheur Metropolitan" },

  // =====================================================================
  // IMPRESSIONISM
  // =====================================================================
  // Monet
  { name: "impression-sunrise.jpg", search: "Impression Sunrise Monet" },
  { name: "water-lilies.jpg", search: "Water Lilies Monet Ryerson" },
  { name: "water-lilies-green.jpg", search: "Water Lilies Monet 1916 green" },
  { name: "water-lilies-large-monet.jpg", search: "Water Lilies Nympheas Monet Orangerie" },
  { name: "japanese-bridge.jpg", search: "Japanese Bridge Water Lilies Monet" },
  { name: "rouen-cathedral.jpg", search: "Rouen Cathedral Monet facade sunset" },
  { name: "haystacks-monet.jpg", search: "Haystacks Grainstacks Monet" },
  { name: "woman-with-parasol-monet.jpg", search: "Woman Parasol Madame Monet Son" },
  { name: "poppy-field-monet.jpg", search: "Poppy Field Monet Argenteuil" },
  { name: "la-grenouillere-monet.jpg", search: "Grenouillère Monet" },
  { name: "gare-saint-lazare-monet.jpg", search: "Gare Saint-Lazare Monet" },
  { name: "regatta-argenteuil-monet.jpg", search: "Regatta Argenteuil Monet" },
  { name: "garden-at-giverny-monet.jpg", search: "Artist's Garden Giverny Monet" },
  { name: "palazzo-da-mula-monet.jpg", search: "Palazzo da Mula Venice Monet" },
  { name: "cliff-walk-pourville-monet.jpg", search: "Cliff Walk Pourville Monet" },
  { name: "houses-parliament-monet.jpg", search: "Houses Parliament London Monet sunset" },
  // Renoir
  { name: "bal-du-moulin.jpg", search: "Bal Moulin Galette Renoir" },
  { name: "luncheon-boating-party.jpg", search: "Luncheon Boating Party Renoir" },
  { name: "two-sisters-renoir.jpg", search: "Two Sisters Terrace Renoir" },
  { name: "dance-at-bougival-renoir.jpg", search: "Dance Bougival Renoir" },
  { name: "la-loge-renoir.jpg", search: "La Loge Renoir theatre box" },
  { name: "bathers-renoir.jpg", search: "Large Bathers Renoir" },
  { name: "girls-at-piano-renoir.jpg", search: "Girls Piano Renoir" },
  { name: "la-grenouillere-renoir.jpg", search: "La Grenouillère Renoir" },
  // Degas
  { name: "dance-class-degas.jpg", search: "Ballet Class Degas" },
  { name: "labsinthe-degas.jpg", search: "Absinthe Degas In a Café" },
  { name: "the-star-degas.jpg", search: "L'Étoile Star Dancer Stage Degas" },
  { name: "rehearsal-degas.jpg", search: "Dance Rehearsal Degas" },
  { name: "blue-dancers-degas.jpg", search: "Blue Dancers Degas" },
  { name: "after-bath-degas.jpg", search: "After Bath Woman Drying Herself Degas" },
  { name: "bellelli-family-degas.jpg", search: "Bellelli Family Degas" },
  { name: "at-the-races-degas.jpg", search: "At Races Degas horses" },
  // Pissarro, Sisley, Morisot, Cassatt
  { name: "boulevard-montmartre-pissarro.jpg", search: "Boulevard Montmartre Night Pissarro" },
  { name: "red-roofs-pissarro.jpg", search: "Red Roofs Pissarro" },
  { name: "flood-at-port-marly-sisley.jpg", search: "Flood Port-Marly Sisley" },
  { name: "bridge-at-moret-sisley.jpg", search: "Bridge Moret Sisley" },
  { name: "cradle-morisot.jpg", search: "Cradle Berthe Morisot" },
  { name: "childs-bath-cassatt.jpg", search: "Child's Bath Mary Cassatt" },
  { name: "little-girl-blue-armchair-cassatt.jpg", search: "Little Girl Blue Armchair Cassatt" },
  // Caillebotte
  { name: "paris-street-rainy-day.jpg", search: "Paris Street Rainy Day Caillebotte" },
  { name: "floor-scrapers-caillebotte.jpg", search: "Floor Scrapers Caillebotte" },

  // =====================================================================
  // POST-IMPRESSIONISM
  // =====================================================================
  // Van Gogh
  { name: "starry-night.jpg", wikimedia: "Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg", search: "Starry Night Van Gogh" },
  { name: "starry-night-rhone.jpg", search: "Starry Night Over Rhône Van Gogh" },
  { name: "cafe-terrace-night.jpg", search: "Café Terrace Night Van Gogh" },
  { name: "sunflowers.jpg", search: "Sunflowers Van Gogh" },
  { name: "bedroom-in-arles.jpg", search: "Bedroom Arles Van Gogh" },
  { name: "irises-vangogh.jpg", search: "Irises Van Gogh" },
  { name: "almond-blossom.jpg", search: "Almond Blossom Van Gogh" },
  { name: "wheatfield-crows.jpg", search: "Wheatfield Crows Van Gogh" },
  { name: "self-portrait-vangogh.jpg", search: "Self Portrait Van Gogh 1889 Musée d'Orsay" },
  { name: "night-cafe-vangogh.jpg", search: "Night Café Van Gogh" },
  { name: "potato-eaters-vangogh.jpg", search: "Potato Eaters Van Gogh" },
  { name: "red-vineyard-vangogh.jpg", search: "Red Vineyard Van Gogh" },
  { name: "self-portrait-bandaged-ear.jpg", search: "Self Portrait Bandaged Ear Van Gogh" },
  { name: "church-at-auvers.jpg", search: "Church Auvers Van Gogh" },
  { name: "wheatfield-cypresses-vangogh.jpg", search: "Wheat Field Cypresses Van Gogh" },
  { name: "sower-vangogh.jpg", search: "Sower Van Gogh after Millet" },
  { name: "mulberry-tree-vangogh.jpg", search: "Mulberry Tree Van Gogh" },
  { name: "dr-gachet-vangogh.jpg", search: "Portrait Dr Gachet Van Gogh" },
  { name: "road-with-cypress-vangogh.jpg", search: "Road Cypress Star Van Gogh" },
  // Cézanne
  { name: "card-players-cezanne.jpg", search: "Card Players Cézanne" },
  { name: "mont-sainte-victoire.jpg", search: "Mont Sainte-Victoire Cézanne" },
  { name: "bathers-cezanne.jpg", search: "Large Bathers Cézanne" },
  { name: "still-life-apples-cezanne.jpg", search: "Still Life Apples Cézanne" },
  { name: "basket-apples-cezanne.jpg", search: "Basket Apples Cézanne Chicago" },
  { name: "boy-red-vest-cezanne.jpg", search: "Boy Red Vest Cézanne" },
  { name: "bibemus-quarries-cezanne.jpg", search: "Bibémus Quarries Cézanne" },
  // Gauguin
  { name: "where-do-we-come-from-gauguin.jpg", search: "Where Do We Come From Gauguin" },
  { name: "yellow-christ-gauguin.jpg", search: "Yellow Christ Gauguin" },
  { name: "vision-after-sermon.jpg", search: "Vision After Sermon Gauguin" },
  { name: "tahitian-women-gauguin.jpg", search: "Tahitian Women Beach Gauguin" },
  { name: "spirit-of-dead-watching-gauguin.jpg", search: "Spirit Dead Watching Gauguin Manao tupapau" },
  { name: "arearea-gauguin.jpg", search: "Arearea Gauguin dog" },
  { name: "when-will-you-marry-gauguin.jpg", search: "When Will You Marry Gauguin Nafea" },
  { name: "self-portrait-yellow-christ-gauguin.jpg", search: "Self Portrait Yellow Christ Gauguin" },
  // Seurat
  { name: "sunday-grande-jatte.jpg", search: "Sunday Afternoon Grande Jatte Seurat" },
  { name: "bathers-asnieres-seurat.jpg", search: "Bathers Asnières Seurat" },
  { name: "circus-seurat.jpg", search: "Circus Seurat Le Cirque" },
  { name: "chahut-seurat.jpg", search: "Le Chahut Seurat" },
  // Toulouse-Lautrec
  { name: "toulouse-lautrec-moulin-rouge.jpg", search: "Moulin Rouge La Goulue Toulouse-Lautrec" },
  { name: "at-moulin-rouge-lautrec.jpg", search: "At Moulin Rouge Toulouse-Lautrec" },
  { name: "jane-avril-lautrec.jpg", search: "Jane Avril Toulouse-Lautrec" },
  // Rousseau
  { name: "sleeping-gypsy.jpg", search: "Sleeping Gypsy Rousseau" },
  { name: "the-dream-rousseau.jpg", search: "Dream Rousseau" },
  { name: "surprised-tiger-rousseau.jpg", search: "Surprised! Tiger Storm Rousseau" },
  { name: "snake-charmer-rousseau.jpg", search: "Snake Charmer Rousseau" },

  // =====================================================================
  // SYMBOLISM & ART NOUVEAU
  // =====================================================================
  { name: "the-scream.jpg", search: "Scream Edvard Munch" },
  { name: "madonna-munch.jpg", search: "Madonna Edvard Munch" },
  { name: "vampire-munch.jpg", search: "Vampire Munch" },
  { name: "puberty-munch.jpg", search: "Puberty Munch" },
  { name: "dance-of-life-munch.jpg", search: "Dance Life Munch" },
  { name: "the-kiss-klimt.jpg", search: "Kiss Klimt" },
  { name: "tree-of-life-klimt.jpg", search: "Tree Life Klimt Stoclet" },
  { name: "death-and-life-klimt.jpg", search: "Death Life Klimt" },
  { name: "portrait-adele-bloch-bauer.jpg", search: "Portrait Adele Bloch-Bauer Klimt" },
  { name: "judith-klimt.jpg", search: "Judith I Klimt" },
  { name: "danae-klimt.jpg", search: "Danaë Klimt" },
  { name: "water-serpents-klimt.jpg", search: "Water Serpents Klimt" },
  { name: "beethoven-frieze-klimt.jpg", search: "Beethoven Frieze Klimt" },
  { name: "orpheus-moreau.jpg", search: "Orpheus Gustave Moreau" },
  { name: "oedipus-sphinx-moreau.jpg", search: "Oedipus Sphinx Moreau" },
  { name: "hope-watts.jpg", search: "Hope George Frederic Watts" },
  { name: "self-portrait-egon-schiele.jpg", search: "Self Portrait Egon Schiele" },
  { name: "embrace-schiele.jpg", search: "Embrace Egon Schiele" },
  { name: "death-and-maiden-schiele.jpg", search: "Death Maiden Egon Schiele" },

  // =====================================================================
  // EXPRESSIONISM
  // =====================================================================
  // Kandinsky
  { name: "composition-viii-kandinsky.jpg", search: "Composition VIII Kandinsky" },
  { name: "several-circles-kandinsky.jpg", search: "Several Circles Kandinsky" },
  { name: "yellow-red-blue-kandinsky.jpg", search: "Yellow Red Blue Kandinsky" },
  { name: "blue-rider-kandinsky.jpg", search: "Blue Rider Der Blaue Reiter Kandinsky" },
  { name: "composition-vii-kandinsky.jpg", search: "Composition VII Kandinsky" },
  { name: "improvisation-28-kandinsky.jpg", search: "Improvisation 28 Kandinsky" },
  { name: "on-white-ii-kandinsky.jpg", search: "On White II Kandinsky" },
  // Marc
  { name: "large-blue-horses-marc.jpg", search: "Large Blue Horses Franz Marc" },
  { name: "fate-of-animals-marc.jpg", search: "Fate Animals Franz Marc" },
  { name: "tiger-marc.jpg", search: "Tiger Franz Marc" },
  { name: "foxes-marc.jpg", search: "Foxes Franz Marc" },
  { name: "yellow-cow-marc.jpg", search: "Yellow Cow Franz Marc" },
  // Klee
  { name: "senecio-klee.jpg", search: "Senecio Klee" },
  { name: "twittering-machine-klee.jpg", search: "Twittering Machine Klee" },
  { name: "red-balloon-klee.jpg", search: "Red Balloon Klee" },
  { name: "fish-magic-klee.jpg", search: "Fish Magic Klee" },
  { name: "highway-and-byways-klee.jpg", search: "Highway Byways Klee" },
  { name: "castle-and-sun-klee.jpg", search: "Castle Sun Klee" },
  // Other Expressionists
  { name: "self-portrait-soldier-kirchner.jpg", search: "Self Portrait Soldier Kirchner" },
  { name: "street-berlin-kirchner.jpg", search: "Street Berlin Kirchner" },
  { name: "prophet-nolde.jpg", search: "Prophet Emil Nolde" },
  { name: "blue-mountain-kandinsky.jpg", search: "Blue Mountain Kandinsky" },

  // =====================================================================
  // ABSTRACT, DE STIJL & SUPREMATISM
  // =====================================================================
  { name: "composition-red-blue-yellow-mondrian.jpg", search: "Composition Red Blue Yellow Mondrian" },
  { name: "broadway-boogie-woogie.jpg", search: "Broadway Boogie Woogie Mondrian" },
  { name: "tableau-i-mondrian.jpg", search: "Tableau I Mondrian" },
  { name: "victory-boogie-woogie-mondrian.jpg", search: "Victory Boogie Woogie Mondrian" },
  { name: "gray-tree-mondrian.jpg", search: "Gray Tree Mondrian" },
  { name: "black-square-malevich.jpg", search: "Black Square Malevich" },
  { name: "suprematist-composition-malevich.jpg", search: "Suprematist Composition Malevich" },
  { name: "white-on-white-malevich.jpg", search: "White White Malevich" },
  { name: "red-square-malevich.jpg", search: "Red Square Painterly Realism Malevich" },
  { name: "black-circle-malevich.jpg", search: "Black Circle Malevich" },

  // =====================================================================
  // CUBISM, FAUVISM & EARLY MODERN
  // =====================================================================
  // Picasso
  { name: "guernica-picasso.jpg", search: "Guernica Picasso" },
  { name: "demoiselles-davignon.jpg", search: "Les Demoiselles d'Avignon Picasso" },
  { name: "old-guitarist-picasso.jpg", search: "Old Guitarist Picasso blue period" },
  { name: "weeping-woman-picasso.jpg", search: "Weeping Woman Picasso" },
  { name: "girl-before-mirror-picasso.jpg", search: "Girl Before Mirror Picasso" },
  { name: "three-musicians-picasso.jpg", search: "Three Musicians Picasso" },
  { name: "la-vie-picasso.jpg", search: "La Vie Picasso blue period" },
  { name: "boy-leading-horse-picasso.jpg", search: "Boy Leading Horse Picasso" },
  { name: "seated-nude-picasso.jpg", search: "Les Femmes d'Alger Picasso" },
  { name: "portrait-dora-maar-picasso.jpg", search: "Portrait Dora Maar Picasso" },
  { name: "dream-picasso.jpg", search: "Le Rêve Dream Picasso 1932" },
  { name: "family-saltimbanques-picasso.jpg", search: "Family Saltimbanques Picasso" },
  { name: "portrait-ambroise-vollard-picasso.jpg", search: "Portrait Ambroise Vollard Picasso cubist" },
  { name: "ma-jolie-picasso.jpg", search: "Ma Jolie Picasso" },
  { name: "harlequin-picasso.jpg", search: "Seated Harlequin Picasso" },
  // Matisse
  { name: "dance-matisse.jpg", search: "Dance Matisse Hermitage" },
  { name: "joy-of-life-matisse.jpg", search: "Joy Life Bonheur Vivre Matisse" },
  { name: "red-studio-matisse.jpg", search: "Red Studio Matisse" },
  { name: "woman-with-hat-matisse.jpg", search: "Woman Hat Matisse" },
  { name: "harmony-in-red-matisse.jpg", search: "Harmony Red Desserte Matisse" },
  { name: "dance-ii-matisse.jpg", search: "Music Matisse Hermitage" },
  { name: "open-window-matisse.jpg", search: "Open Window Collioure Matisse" },
  { name: "blue-nudes-matisse.jpg", search: "Blue Nude Matisse" },
  { name: "icarus-matisse.jpg", search: "Icarus Matisse Jazz" },
  // Duchamp, Braque, Léger
  { name: "nude-descending-staircase.jpg", search: "Nude Descending Staircase Duchamp" },
  { name: "violin-candlestick-braque.jpg", search: "Violin Candlestick Braque cubist" },
  { name: "houses-estaque-braque.jpg", search: "Houses L'Estaque Braque" },
  { name: "city-leger.jpg", search: "City Fernand Léger" },
  { name: "three-women-leger.jpg", search: "Three Women Grand Déjeuner Léger" },
  // Modigliani
  { name: "reclining-nude-modigliani.jpg", search: "Reclining Nude Modigliani" },
  { name: "jeanne-hebuterne-modigliani.jpg", search: "Jeanne Hébuterne Modigliani" },

  // =====================================================================
  // SURREALISM
  // =====================================================================
  // Dalí
  { name: "persistence-of-memory.jpg", search: "Persistence Memory Dalí" },
  { name: "elephants-dali.jpg", search: "Elephants Dalí" },
  { name: "burning-giraffe-dali.jpg", search: "Burning Giraffe Dalí" },
  { name: "swans-reflecting-elephants-dali.jpg", search: "Swans Reflecting Elephants Dalí" },
  { name: "metamorphosis-narcissus-dali.jpg", search: "Metamorphosis Narcissus Dalí" },
  { name: "great-masturbator-dali.jpg", search: "Great Masturbator Dalí" },
  { name: "christ-st-john-cross-dali.jpg", search: "Christ Saint John Cross Dalí" },
  { name: "galatea-spheres-dali.jpg", search: "Galatea Spheres Dalí" },
  // Magritte
  { name: "son-of-man-magritte.jpg", search: "Son Man Magritte" },
  { name: "treachery-of-images-magritte.jpg", search: "Treachery Images Magritte Ceci n'est pas une pipe" },
  { name: "lovers-magritte.jpg", search: "Lovers Magritte veiled" },
  { name: "empire-of-light-magritte.jpg", search: "Empire Light Magritte" },
  { name: "golconda-magritte.jpg", search: "Golconda Magritte" },
  { name: "false-mirror-magritte.jpg", search: "False Mirror Magritte eye" },
  { name: "human-condition-magritte.jpg", search: "Human Condition Magritte" },
  // Others
  { name: "i-and-the-village-chagall.jpg", search: "I Village Chagall" },
  { name: "birthday-chagall.jpg", search: "Birthday Chagall flying" },
  { name: "over-the-town-chagall.jpg", search: "Over Town Chagall Vitebsk" },
  { name: "white-crucifixion-chagall.jpg", search: "White Crucifixion Chagall" },
  { name: "harlequins-carnival-miro.jpg", search: "Harlequin's Carnival Miró" },
  { name: "constellations-miro.jpg", search: "Constellations Miró Beautiful Bird" },
  { name: "elephant-celebes-ernst.jpg", search: "Elephant Celebes Max Ernst" },
  { name: "eye-of-silence-ernst.jpg", search: "Eye Silence Max Ernst" },
  { name: "two-fridas-kahlo.jpg", search: "Two Fridas Kahlo" },
  { name: "self-portrait-thorn-necklace-kahlo.jpg", search: "Self Portrait Thorn Necklace Kahlo" },
  { name: "henry-ford-hospital-kahlo.jpg", search: "Henry Ford Hospital Kahlo" },

  // =====================================================================
  // RUSSIAN & EASTERN EUROPEAN
  // =====================================================================
  { name: "ivan-terrible-repin.jpg", search: "Ivan Terrible Son Repin" },
  { name: "barge-haulers-repin.jpg", search: "Barge Haulers Volga Repin" },
  { name: "unexpected-visitors-repin.jpg", search: "Unexpected Visitors Repin" },
  { name: "reply-zaporozhian-cossacks-repin.jpg", search: "Reply Zaporozhian Cossacks Repin" },
  { name: "ninth-wave-aivazovsky.jpg", search: "Ninth Wave Aivazovsky" },
  { name: "storm-sea-night-aivazovsky.jpg", search: "Storm Sea Night Aivazovsky" },
  { name: "among-waves-aivazovsky.jpg", search: "Among Waves Aivazovsky" },
  { name: "morning-pine-forest-shishkin.jpg", search: "Morning Pine Forest Shishkin bears" },
  { name: "rooks-have-returned-savrasov.jpg", search: "Rooks Have Returned Savrasov" },
  { name: "princess-dream-vrubel.jpg", search: "Demon Seated Vrubel" },
  { name: "over-city-chagall.jpg", search: "Promenade Chagall floating" },
  { name: "bathing-red-horse-petrov-vodkin.jpg", search: "Bathing Red Horse Petrov-Vodkin" },
  { name: "black-cross-malevich.jpg", search: "Black Cross Malevich" },

  // =====================================================================
  // UKIYO-E & ASIAN ART
  // =====================================================================
  // Hokusai
  { name: "great-wave.jpg", wikimedia: "Tsunami_by_hokusai_19th_century.jpg", search: "Great Wave Kanagawa Hokusai" },
  { name: "fine-wind-clear-morning.jpg", search: "Fine Wind Clear Morning Hokusai Red Fuji" },
  { name: "ejiri-in-suruga-hokusai.jpg", search: "Ejiri Suruga Province Hokusai wind" },
  { name: "thunderstorm-beneath-summit-hokusai.jpg", search: "Thunderstorm Beneath Summit Hokusai Fuji" },
  { name: "kajikazawa-hokusai.jpg", search: "Kajikazawa Kai Province Hokusai fisherman" },
  { name: "phoenix-hokusai.jpg", search: "Phoenix Hokusai" },
  { name: "dragon-hokusai.jpg", search: "Dragon ascending Hokusai" },
  { name: "dream-fishermans-wife-hokusai.jpg", search: "Dream Fisherman's Wife Hokusai octopus" },
  // Hiroshige
  { name: "plum-garden-hiroshige.jpg", search: "Plum Garden Kameido Hiroshige" },
  { name: "sudden-shower-hiroshige.jpg", search: "Sudden Shower Ohashi Bridge Hiroshige" },
  { name: "station-otsu-hiroshige.jpg", search: "Fifty-three Stations Tōkaidō Hiroshige" },
  { name: "moon-over-ships-hiroshige.jpg", search: "Moon Hiroshige Tsukuda" },
  { name: "whirlpool-naruto-hiroshige.jpg", search: "Whirlpool Naruto Hiroshige" },
  // Other
  { name: "autumn-moon-hiroshige.jpg", search: "Autumn Moon Tama River Hiroshige" },
  { name: "thirty-six-views-sharaku.jpg", search: "Actor Otani Oniji Sharaku" },
  { name: "bijin-okubi-utamaro.jpg", search: "Utamaro Three Beauties" },
  { name: "cranes-painting-jakuchu.jpg", search: "Rooster Hen Jakuchu" },
  { name: "wind-god-thunder-god-sotatsu.jpg", search: "Wind God Thunder God Sōtatsu" },

  // =====================================================================
  // AMERICAN ART
  // =====================================================================
  { name: "american-gothic.jpg", search: "American Gothic Grant Wood" },
  { name: "washington-crossing-delaware.jpg", search: "Washington Crossing Delaware Leutze" },
  { name: "watson-and-shark.jpg", search: "Watson Shark Copley" },
  { name: "nighthawks-hopper.jpg", search: "Nighthawks Edward Hopper" },
  { name: "freedom-from-want-rockwell.jpg", search: "Freedom Want Norman Rockwell Thanksgiving" },
  { name: "breezing-up-homer.jpg", search: "Breezing Up Fair Wind Winslow Homer" },
  { name: "fog-warning-homer.jpg", search: "Fog Warning Winslow Homer" },
  { name: "gulf-stream-homer.jpg", search: "Gulf Stream Winslow Homer" },
  { name: "snap-the-whip-homer.jpg", search: "Snap Whip Winslow Homer" },
  { name: "christinas-world-wyeth.jpg", search: "Christina's World Andrew Wyeth" },
  { name: "office-night-hopper.jpg", search: "Office Night Hopper" },
  { name: "automat-hopper.jpg", search: "Automat Hopper" },
  { name: "gas-hopper.jpg", search: "Gas Hopper" },
  { name: "morning-sun-hopper.jpg", search: "Morning Sun Hopper" },
  { name: "room-in-new-york-hopper.jpg", search: "Room New York Hopper" },
  { name: "chop-suey-hopper.jpg", search: "Chop Suey Hopper" },
  { name: "rocky-mountains-bierstadt.jpg", search: "Rocky Mountains Lander's Peak Bierstadt" },
  { name: "among-sierra-nevada-bierstadt.jpg", search: "Among Sierra Nevada Bierstadt" },
  { name: "kindred-spirits-durand.jpg", search: "Kindred Spirits Asher Durand" },
  { name: "sargent-madame-x.jpg", search: "Madame X Sargent" },
  { name: "daughters-boit-sargent.jpg", search: "Daughters Edward Darley Boit Sargent" },
  { name: "arrangement-grey-black-2-whistler.jpg", search: "Nocturne Blue Gold Old Battersea Whistler" },

  // =====================================================================
  // ABSTRACT EXPRESSIONISM & POST-WAR
  // =====================================================================
  { name: "no-5-pollock.jpg", search: "Number 1A Pollock 1948" },
  { name: "autumn-rhythm-pollock.jpg", search: "Autumn Rhythm Number 30 Pollock" },
  { name: "convergence-pollock.jpg", search: "Convergence Pollock" },
  { name: "no-61-rothko.jpg", search: "No 61 Rust Blue Rothko" },
  { name: "orange-red-yellow-rothko.jpg", search: "Orange Red Yellow Rothko" },
  { name: "woman-i-de-kooning.jpg", search: "Woman I de Kooning" },
  { name: "excavation-de-kooning.jpg", search: "Excavation de Kooning" },
  { name: "elegy-spanish-republic-motherwell.jpg", search: "Elegy Spanish Republic Motherwell" },
  { name: "mountains-sea-frankenthaler.jpg", search: "Mountains Sea Helen Frankenthaler" },
  { name: "who-afraid-red-yellow-blue-newman.jpg", search: "Who's Afraid Red Yellow Blue Newman" },
  { name: "vir-heroicus-sublimis-newman.jpg", search: "Vir Heroicus Sublimis Newman" },
  { name: "onement-newman.jpg", search: "Onement I Barnett Newman" },
  { name: "untitled-1950-franz-kline.jpg", search: "Chief Franz Kline" },
  { name: "sky-above-clouds-okeeffe.jpg", search: "Sky Above Clouds O'Keeffe" },
  { name: "jimson-weed-okeeffe.jpg", search: "Jimson Weed White Flower O'Keeffe" },
  { name: "red-canna-okeeffe.jpg", search: "Red Canna O'Keeffe" },
  { name: "rams-head-okeeffe.jpg", search: "Ram's Head Blue Morning Glory O'Keeffe" },

  // =====================================================================
  // POP ART & CONTEMPORARY
  // =====================================================================
  { name: "campbells-soup-warhol.jpg", search: "Campbell's Soup Cans Warhol" },
  { name: "marilyn-diptych-warhol.jpg", search: "Marilyn Diptych Warhol" },
  { name: "whaam-lichtenstein.jpg", search: "Whaam! Lichtenstein" },
  { name: "drowning-girl-lichtenstein.jpg", search: "Drowning Girl Lichtenstein" },
  { name: "flag-jasper-johns.jpg", search: "Flag Jasper Johns" },
  { name: "three-flags-johns.jpg", search: "Three Flags Jasper Johns" },
  { name: "just-what-is-it-hamilton.jpg", search: "Just What Is It Makes Today's Homes Hamilton" },
  { name: "bigger-splash-hockney.jpg", search: "Bigger Splash David Hockney" },
  { name: "mr-mrs-clark-hockney.jpg", search: "Mr Mrs Clark Percy Hockney" },
  { name: "portrait-artist-pool-hockney.jpg", search: "Portrait Artist Pool Two Figures Hockney" },
  { name: "love-indiana.jpg", search: "LOVE Robert Indiana" },
  { name: "balloon-dog-koons.jpg", search: "Balloon Dog Jeff Koons" },
  { name: "girl-with-balloon-banksy.jpg", search: "Girl Balloon Banksy" },
  { name: "obey-giant-shepard-fairey.jpg", search: "Hope Obama Shepard Fairey" },

  // =====================================================================
  // ADDITIONAL WORLD MASTERWORKS
  // =====================================================================
  // Vermeer — extra
  { name: "concert-vermeer.jpg", search: "Concert Vermeer stolen" },
  { name: "woman-with-pearl-necklace-vermeer.jpg", search: "Woman Pearl Necklace Vermeer" },
  // Rubens — extra
  { name: "rape-daughters-leucippus-rubens.jpg", search: "Rape Daughters Leucippus Rubens" },
  { name: "helena-fourment-fur-rubens.jpg", search: "Helena Fourment Fur Rubens" },
  // More old masters
  { name: "conversion-paul-tintoretto.jpg", search: "Last Supper Tintoretto San Giorgio Maggiore" },
  { name: "paradise-tintoretto.jpg", search: "Paradise Tintoretto Doge's Palace" },
  { name: "supper-at-emmaus-pontormo.jpg", search: "Supper Emmaus Pontormo" },
  { name: "st-sebastian-mantegna.jpg", search: "Saint Sebastian Mantegna" },
  { name: "dead-christ-mantegna.jpg", search: "Lamentation Dead Christ Mantegna foreshortened" },
  { name: "portrait-doge-bellini.jpg", search: "Doge Leonardo Loredan Bellini" },
  { name: "feast-of-gods-bellini.jpg", search: "Feast Gods Giovanni Bellini" },
  { name: "judith-giorgione.jpg", search: "Judith Giorgione Hermitage" },
  // Georges de La Tour
  { name: "magdalene-two-flames-la-tour.jpg", search: "Magdalene Two Flames Georges La Tour" },
  { name: "cheat-ace-diamonds-la-tour.jpg", search: "Cheat Ace Diamonds La Tour" },
  // Zurbarán
  { name: "saint-serapion-zurbaran.jpg", search: "Saint Serapion Zurbarán" },
  { name: "still-life-lemons-zurbaran.jpg", search: "Still Life Lemons Oranges Zurbarán" },
  // More landscapes & misc
  { name: "scream-across-bridge-munch.jpg", search: "Anxiety Munch bridge" },
  { name: "starry-night-munch.jpg", search: "Starry Night Edvard Munch" },
  { name: "girls-on-pier-munch.jpg", search: "Girls Pier Munch" },
  { name: "sick-child-munch.jpg", search: "Sick Child Munch" },
  { name: "spring-munch.jpg", search: "Spring Munch" },
  { name: "letter-vermeer-blue.jpg", search: "Woman Blue Reading Letter Vermeer" },
  { name: "peasant-dance-bruegel.jpg", search: "Peasant Dance Bruegel" },
  { name: "children-games-bruegel.jpg", search: "Children's Games Bruegel" },
  { name: "census-bethlehem-bruegel.jpg", search: "Census Bethlehem Bruegel" },
  { name: "adoration-shepherds-la-tour.jpg", search: "Adoration Shepherds La Tour" },
  { name: "young-woman-water-pitcher-vermeer.jpg", search: "Young Woman Water Pitcher Vermeer" },

  // =====================================================================
  // MORE RENAISSANCE & OLD MASTERS
  // =====================================================================
  { name: "assumption-virgin-correggio.jpg", search: "Assumption Virgin Correggio Parma dome" },
  { name: "jupiter-io-correggio.jpg", search: "Jupiter Io Correggio" },
  { name: "madonna-of-the-chair-raphael.jpg", search: "Madonna Chair Raphael Pitti" },
  { name: "madonna-of-the-meadow-raphael.jpg", search: "Madonna Meadow Raphael Vienna" },
  { name: "deposition-raphael-borghese.jpg", search: "Deposition Raphael Borghese" },
  { name: "st-francis-ecstasy-bellini.jpg", search: "Saint Francis Ecstasy Giovanni Bellini Frick" },
  { name: "coronation-virgin-fra-angelico.jpg", search: "Coronation Virgin Fra Angelico Uffizi" },
  { name: "battle-alexander-altdorfer.jpg", search: "Battle Alexander Issus Altdorfer" },
  { name: "isenheim-altarpiece.jpg", search: "Isenheim Altarpiece Grünewald crucifixion" },
  { name: "ambassadors-death-holbein.jpg", search: "Dance Death Holbein" },
  { name: "rest-on-flight-egypt-cranach.jpg", search: "Rest Flight Egypt Lucas Cranach" },
  { name: "venus-cranach.jpg", search: "Venus Cupid Cranach" },
  { name: "judith-cranach.jpg", search: "Judith Head Holofernes Cranach" },
  { name: "marriage-giovanni-cenami-eyck.jpg", search: "Lucca Madonna Jan van Eyck" },
  { name: "deposition-pontormo.jpg", search: "Deposition Pontormo Santa Felicita" },
  { name: "allegory-venus-bronzino.jpg", search: "Allegory Venus Cupid Folly Time Bronzino" },
  { name: "concert-champetre.jpg", search: "Pastoral Concert Giorgione Titian Louvre" },
  { name: "pesaro-madonna-titian.jpg", search: "Pesaro Madonna Titian" },
  { name: "entombment-titian.jpg", search: "Entombment Titian" },
  { name: "venus-mirror-titian.jpg", search: "Venus Mirror Titian" },

  // =====================================================================
  // MORE BAROQUE & 17TH CENTURY
  // =====================================================================
  { name: "charles-i-van-dyck.jpg", search: "Charles I Hunting Van Dyck" },
  { name: "self-portrait-sunflower-van-dyck.jpg", search: "Self Portrait Van Dyck" },
  { name: "boy-bitten-lizard-caravaggio.jpg", search: "Boy Bitten Lizard Caravaggio" },
  { name: "fortune-teller-caravaggio.jpg", search: "Fortune Teller Caravaggio" },
  { name: "seven-works-mercy-caravaggio.jpg", search: "Seven Works Mercy Caravaggio Naples" },
  { name: "crucifixion-st-peter-caravaggio.jpg", search: "Crucifixion Saint Peter Caravaggio" },
  { name: "embarkation-queen-sheba-lorrain.jpg", search: "Embarkation Queen Sheba Claude Lorrain" },
  { name: "landscape-claude-lorrain.jpg", search: "Landscape Hagar Angel Claude Lorrain" },
  { name: "penitent-magdalene-la-tour.jpg", search: "Penitent Magdalene Georges La Tour candle" },
  { name: "maid-servant-kitchen-vermeer.jpg", search: "Christ House Martha Mary Vermeer" },
  { name: "girl-wineglass-vermeer.jpg", search: "Girl Wine Glass Vermeer" },
  { name: "man-golden-helmet-rembrandt.jpg", search: "Man Golden Helmet Rembrandt Berlin" },
  { name: "danae-rembrandt.jpg", search: "Danaë Rembrandt Hermitage" },
  { name: "self-portrait-1640-rembrandt.jpg", search: "Self Portrait Age 34 Rembrandt National Gallery" },
  { name: "anatomy-lesson-deijman-rembrandt.jpg", search: "Anatomy Lesson Dr Deijman Rembrandt" },
  { name: "old-man-red-rembrandt.jpg", search: "Old Man Red Rembrandt Hermitage" },
  { name: "las-hilanderas-velazquez-2.jpg", search: "Spinners Las Hilanderas Velázquez" },
  { name: "triumph-bacchus-velazquez.jpg", search: "Triumph Bacchus Los Borrachos Velázquez" },
  { name: "mars-resting-velazquez.jpg", search: "Mars Resting Velázquez Prado" },

  // =====================================================================
  // MORE IMPRESSIONISM & POST-IMPRESSIONISM
  // =====================================================================
  { name: "san-giorgio-maggiore-monet.jpg", search: "San Giorgio Maggiore Twilight Monet" },
  { name: "charing-cross-bridge-monet.jpg", search: "Charing Cross Bridge Monet Thames" },
  { name: "autumn-effect-argenteuil-monet.jpg", search: "Autumn Effect Argenteuil Monet" },
  { name: "bridge-argenteuil-monet.jpg", search: "Bridge Argenteuil Monet" },
  { name: "la-japonaise-monet.jpg", search: "La Japonaise Monet Camille kimono" },
  { name: "seine-at-lavacourt-monet.jpg", search: "Seine Lavacourt Winter Monet" },
  { name: "umbrellas-renoir.jpg", search: "Umbrellas Renoir National Gallery" },
  { name: "dance-city-renoir.jpg", search: "Dance City Renoir" },
  { name: "dance-country-renoir.jpg", search: "Dance Country Renoir" },
  { name: "swing-renoir.jpg", search: "Swing La Balançoire Renoir" },
  { name: "nude-sunlight-renoir.jpg", search: "Nude Sunlight Renoir" },
  { name: "fourteen-year-old-dancer-degas.jpg", search: "Little Dancer Fourteen Years Degas sculpture" },
  { name: "ironing-woman-degas.jpg", search: "Ironers Woman Ironing Degas" },
  { name: "miss-la-la-cirque-degas.jpg", search: "Miss La La Cirque Fernando Degas" },
  { name: "jockey-before-start-degas.jpg", search: "Race Horses Degas" },
  { name: "berthe-morisot-reading.jpg", search: "Reading Berthe Morisot" },
  { name: "summer-day-morisot.jpg", search: "Summer Day Morisot" },
  { name: "boating-cassatt.jpg", search: "Boating Party Cassatt" },
  { name: "boulevard-des-italiens-pissarro.jpg", search: "Boulevard des Italiens Morning Sunlight Pissarro" },
  { name: "entrance-village-voisins-pissarro.jpg", search: "Entrance Village Voisins Pissarro" },
  { name: "moret-sur-loing-sisley.jpg", search: "Moret-sur-Loing Sisley" },
  { name: "snow-at-louveciennes-sisley.jpg", search: "Snow Louveciennes Sisley" },
  // More Van Gogh
  { name: "olive-trees-vangogh.jpg", search: "Olive Trees Van Gogh" },
  { name: "garden-of-the-asylum-vangogh.jpg", search: "Garden Asylum Saint-Rémy Van Gogh" },
  { name: "red-vineyards-vangogh-2.jpg", search: "Vincent's Bedroom Arles Van Gogh second version" },
  { name: "terrace-garden-vangogh.jpg", search: "Garden Daubigny Van Gogh" },
  { name: "prisoners-exercising-vangogh.jpg", search: "Prisoners Exercising Round Van Gogh" },
  { name: "shoes-vangogh.jpg", search: "Pair Shoes Van Gogh" },
  { name: "fishing-boats-saintes-maries.jpg", search: "Fishing Boats Beach Saintes-Maries Van Gogh" },
  // More Cézanne
  { name: "apples-oranges-cezanne.jpg", search: "Apples Oranges Cézanne" },
  { name: "lac-dannecy-cezanne.jpg", search: "Lac d'Annecy Cézanne" },
  { name: "chestnut-trees-jas-bouffan-cezanne.jpg", search: "Jas Bouffan Cézanne" },
  { name: "self-portrait-cezanne.jpg", search: "Self Portrait Cézanne" },
  { name: "gardanne-cezanne.jpg", search: "Gardanne Cézanne" },
  // More Gauguin
  { name: "la-orana-maria-gauguin.jpg", search: "Ia Orana Maria Gauguin" },
  { name: "nevermore-gauguin.jpg", search: "Nevermore Gauguin" },
  { name: "mahana-no-atua-gauguin.jpg", search: "Mahana no Atua Day God Gauguin" },
  { name: "market-gauguin.jpg", search: "Ta Matete Market Gauguin" },
  // More Seurat & Signac
  { name: "models-seurat.jpg", search: "Models Les Poseuses Seurat" },
  { name: "eiffel-tower-seurat.jpg", search: "Eiffel Tower Seurat" },
  { name: "pine-tree-signac.jpg", search: "Pine Tree Saint-Tropez Signac" },
  { name: "port-saint-tropez-signac.jpg", search: "Port Saint-Tropez Signac" },

  // =====================================================================
  // MORE EXPRESSIONISM & MODERN
  // =====================================================================
  { name: "with-black-arch-kandinsky.jpg", search: "With Black Arch Kandinsky" },
  { name: "composition-iv-kandinsky.jpg", search: "Composition IV Kandinsky" },
  { name: "in-grey-kandinsky.jpg", search: "In Grey Kandinsky" },
  { name: "autumn-landscape-kandinsky.jpg", search: "Autumn Landscape Murnau Kandinsky" },
  { name: "deer-in-forest-marc.jpg", search: "Deer Forest Marc II" },
  { name: "blue-horse-i-marc.jpg", search: "Blue Horse I Franz Marc" },
  { name: "small-pleasures-kandinsky.jpg", search: "Small Pleasures Kandinsky" },
  { name: "angel-of-the-hearth-ernst.jpg", search: "Angel Hearth Max Ernst" },
  { name: "europe-after-rain-ernst.jpg", search: "Europe After Rain Ernst" },
  { name: "persistence-memory-dali-2.jpg", search: "Disintegration Persistence Memory Dalí" },
  { name: "soft-construction-dali.jpg", search: "Soft Construction Boiled Beans Premonition Civil War Dalí" },
  { name: "temptation-st-anthony-dali.jpg", search: "Temptation Saint Anthony Dalí elephants" },
  { name: "face-mae-west-dali.jpg", search: "Face Mae West Dalí" },

  // =====================================================================
  // MORE ABSTRACT & CONTEMPORARY
  // =====================================================================
  { name: "painting-1946-bacon.jpg", search: "Painting 1946 Francis Bacon" },
  { name: "study-velazquez-bacon.jpg", search: "Study Velazquez Pope Innocent X Bacon screaming" },
  { name: "three-studies-lucian-freud-bacon.jpg", search: "Three Studies Lucian Freud Bacon triptych" },
  { name: "benefits-supervisor-sleeping-freud.jpg", search: "Benefits Supervisor Sleeping Lucian Freud" },
  { name: "standing-by-rags-freud.jpg", search: "Standing Rags Lucian Freud" },
  { name: "green-white-rothko.jpg", search: "Green White Rothko" },
  { name: "no-14-white-greens-blue-rothko.jpg", search: "No 14 White Greens Blue Rothko" },
  { name: "black-in-deep-red-rothko.jpg", search: "Black Deep Red Rothko" },
  { name: "blue-poles-pollock.jpg", search: "Blue Poles Pollock" },
  { name: "mural-pollock.jpg", search: "Mural 1943 Jackson Pollock" },
  { name: "interchange-de-kooning.jpg", search: "Interchange de Kooning" },
  { name: "athenian-garden-twombly.jpg", search: "Cy Twombly Untitled" },
  { name: "no-6-still.jpg", search: "Clyfford Still 1949 painting" },
  { name: "yellow-islands-johns.jpg", search: "Map Jasper Johns" },
  { name: "target-with-four-faces-johns.jpg", search: "Target Four Faces Jasper Johns" },

  // =====================================================================
  // MORE WORLD ART
  // =====================================================================
  { name: "wanderer-above-sea-fog-2.jpg", search: "Woman in the Sun Edward Hopper" },
  { name: "cape-cod-evening-hopper.jpg", search: "Cape Cod Evening Hopper" },
  { name: "new-york-movie-hopper.jpg", search: "New York Movie Hopper" },
  { name: "sun-empty-room-hopper.jpg", search: "Sun Empty Room Hopper" },
  { name: "house-by-railroad-hopper.jpg", search: "House Railroad Hopper" },
  { name: "second-floor-sunlight-hopper.jpg", search: "Second Floor Sunlight Hopper" },
  { name: "early-sunday-morning-hopper.jpg", search: "Early Sunday Morning Hopper" },
  { name: "oxbow-cole-2.jpg", search: "Voyage Life Thomas Cole" },
  { name: "niagara-church.jpg", search: "Niagara Frederic Edwin Church" },
  { name: "crossing-the-brook-turner.jpg", search: "Crossing Brook Turner" },
  { name: "norham-castle-sunrise-turner.jpg", search: "Norham Castle Sunrise Turner" },
  { name: "dido-building-carthage-turner.jpg", search: "Dido Building Carthage Turner" },
  { name: "ulysses-deriding-polyphemus-turner.jpg", search: "Ulysses Deriding Polyphemus Turner" },
  { name: "tenth-plague-egypt-turner.jpg", search: "Fifth Plague Egypt Turner" },
  { name: "garden-earthly-delights-right.jpg", search: "Garden Earthly Delights Bosch Hell right panel" },
  { name: "last-supper-tintoretto.jpg", search: "Last Supper Tintoretto San Giorgio" },
  { name: "origin-milky-way-tintoretto.jpg", search: "Origin Milky Way Tintoretto" },
  { name: "finding-moses-tintoretto.jpg", search: "Finding Moses Tintoretto" },
  { name: "susanna-elders-tintoretto.jpg", search: "Susanna Elders Tintoretto" },
  { name: "feast-house-levi-veronese.jpg", search: "Feast House Levi Veronese" },
  { name: "mystical-nativity-botticelli.jpg", search: "Mystical Nativity Botticelli" },
  { name: "madonna-pomegranate-botticelli.jpg", search: "Madonna Pomegranate Botticelli" },
  { name: "portrait-young-man-botticelli.jpg", search: "Portrait Young Man Botticelli" },
  { name: "pieta-michelangelo-paint.jpg", search: "Entombment Michelangelo National Gallery" },
  { name: "leda-and-swan-leonardo.jpg", search: "Leda Swan after Leonardo copy" },
  { name: "portrait-musician-leonardo.jpg", search: "Portrait Musician Leonardo da Vinci" },
  { name: "la-belle-ferronniere.jpg", search: "La Belle Ferronnière Leonardo" },
  // More Russian
  { name: "moonlit-night-kuindzhi.jpg", search: "Moonlit Night Dnieper Kuindzhi" },
  { name: "morning-staretz-kramskoi.jpg", search: "Christ Wilderness Kramskoi" },
  { name: "unknown-woman-kramskoi.jpg", search: "Unknown Woman Kramskoi" },
  { name: "demon-vrubel.jpg", search: "Seated Demon Vrubel" },
  { name: "swan-princess-vrubel.jpg", search: "Swan Princess Vrubel" },
  { name: "black-sea-aivazovsky.jpg", search: "Black Sea Aivazovsky" },
  { name: "rainbow-aivazovsky.jpg", search: "Rainbow Aivazovsky" },
  { name: "rye-shishkin.jpg", search: "Rye Shishkin" },
  { name: "rain-oak-forest-shishkin.jpg", search: "Rain Oak Forest Shishkin" },
  // More Asian
  { name: "wave-shore-hokusai.jpg", search: "In Mountains Tōtōmi Province Hokusai" },
  { name: "waterfall-kiso-hokusai.jpg", search: "Amida Falls Hokusai waterfall" },
  { name: "mishima-pass-hokusai.jpg", search: "Mishima Pass Kai Province Hokusai" },
  { name: "nihonbashi-hiroshige.jpg", search: "Nihonbashi Hiroshige morning" },
  { name: "night-snow-kambara-hiroshige.jpg", search: "Night Snow Kambara Hiroshige" },
  { name: "lake-hakone-hiroshige.jpg", search: "Lake Hakone Hiroshige" },
  { name: "iris-garden-horikiri-hiroshige.jpg", search: "Iris Garden Horikiri Hiroshige" },
  { name: "fuji-from-satta-hiroshige.jpg", search: "Suruga Bay Satta Hiroshige" },
  { name: "toto-sumida-river-hiroshige.jpg", search: "Fireworks Ryōgoku Hiroshige" },
  // More Mexican
  { name: "broken-column-kahlo.jpg", search: "Broken Column Frida Kahlo" },
  { name: "memory-heart-kahlo.jpg", search: "Memory Heart Frida Kahlo" },
  { name: "diego-my-mind-kahlo.jpg", search: "Diego My Thoughts Frida Kahlo" },
  { name: "man-crossroads-rivera.jpg", search: "Man Crossroads Diego Rivera" },
  { name: "dream-sunday-alameda-rivera.jpg", search: "Dream Sunday Afternoon Alameda Rivera" },
  { name: "flower-carrier-rivera.jpg", search: "Flower Carrier Diego Rivera" },
  { name: "man-fire-orozco.jpg", search: "Man Fire José Clemente Orozco" },
  { name: "prometheus-orozco.jpg", search: "Prometheus Orozco Pomona" },
  { name: "echo-of-scream-siqueiros.jpg", search: "Echo Scream Siqueiros" },

  // ─── British Art ────────────────────────────────────────────────────────────
  { name: "mr-and-mrs-andrews-gainsborough.jpg", search: "Mr and Mrs Andrews Gainsborough" },
  { name: "mrs-siddons-gainsborough.jpg", search: "Mrs Siddons Reynolds" },
  { name: "rain-steam-speed-turner.jpg", search: "Rain Steam Speed Great Western Railway Turner" },
  { name: "fighting-temeraire-turner2.jpg", search: "Fighting Temeraire Turner National Gallery" },
  { name: "hay-wain-constable.jpg", search: "Hay Wain Constable" },
  { name: "marriage-a-la-mode-hogarth.jpg", search: "Marriage à la Mode Hogarth" },
  { name: "carnation-lily-sargent.jpg", search: "Carnation Lily Lily Rose Sargent" },
  { name: "lady-agnew-sargent.jpg", search: "Lady Agnew Lochnaw Sargent" },
  { name: "madame-x-sargent2.jpg", search: "Madame X Sargent painting" },
  { name: "chatterton-wallis.jpg", search: "Death Chatterton Henry Wallis" },
  { name: "derby-day-frith.jpg", search: "Derby Day William Powell Frith" },
  { name: "last-of-england-brown.jpg", search: "Last of England Ford Madox Brown" },
  { name: "work-ford-madox-brown.jpg", search: "Work Ford Madox Brown painting" },
  { name: "fairy-feller-dadd.jpg", search: "Fairy Feller Master Stroke Dadd" },
  { name: "lady-shalott-waterhouse.jpg", search: "Lady Shalott Waterhouse" },
  { name: "hylas-nymphs-waterhouse.jpg", search: "Hylas Nymphs Waterhouse" },
  { name: "ophelia-waterhouse.jpg", search: "Ophelia Waterhouse" },

  // ─── Dutch Golden Age (additional) ─────────────────────────────────────────
  { name: "banquet-civic-guard-hals.jpg", search: "Officers Saint George Civic Guard Hals" },
  { name: "prodigal-son-rembrandt.jpg", search: "Return Prodigal Son Rembrandt" },
  { name: "anatomy-dr-tulp-rembrandt.jpg", search: "Anatomy Lesson Dr Tulp Rembrandt" },
  { name: "syndics-rembrandt.jpg", search: "Syndics Drapers Guild Rembrandt" },
  { name: "night-watch-detail.jpg", search: "Night Watch Rembrandt detail" },
  { name: "bull-paulus-potter.jpg", search: "Young Bull Paulus Potter" },
  { name: "avenue-middelharnis-hobbema.jpg", search: "Avenue Middelharnis Hobbema" },
  { name: "delft-view-vermeer.jpg", search: "View Delft Vermeer" },
  { name: "woman-balance-vermeer.jpg", search: "Woman Holding Balance Vermeer" },
  { name: "lacemaker-vermeer.jpg", search: "Lacemaker Vermeer" },
  { name: "goldfinch-fabritius.jpg", search: "Goldfinch Carel Fabritius" },

  // ─── Flemish & Northern European ────────────────────────────────────────────
  { name: "arnolfini-portrait-van-eyck.jpg", search: "Arnolfini Portrait Van Eyck" },
  { name: "ghent-altarpiece-van-eyck.jpg", search: "Ghent Altarpiece Van Eyck Adoration" },
  { name: "descent-cross-van-der-weyden.jpg", search: "Descent Cross Rogier van der Weyden" },
  { name: "garden-delights-detail-bosch.jpg", search: "Garden Earthly Delights center Bosch" },
  { name: "ship-fools-bosch.jpg", search: "Ship Fools Bosch" },
  { name: "hunters-snow-bruegel-detail.jpg", search: "Hunters Snow Bruegel painting" },
  { name: "tower-babel-bruegel.jpg", search: "Tower Babel Pieter Bruegel" },
  { name: "fall-icarus-bruegel.jpg", search: "Landscape Fall Icarus Bruegel" },
  { name: "dulle-griet-bruegel.jpg", search: "Dulle Griet Mad Meg Bruegel" },
  { name: "massacre-innocents-bruegel.jpg", search: "Massacre Innocents Bruegel" },
  { name: "self-portrait-durer.jpg", search: "Self Portrait Albrecht Dürer 1500" },
  { name: "praying-hands-durer.jpg", search: "Praying Hands Albrecht Dürer" },
  { name: "ambassadors-holbein.jpg", search: "Ambassadors Hans Holbein" },

  // ─── Spanish Masters (additional) ──────────────────────────────────────────
  { name: "garden-delights-prado.jpg", search: "Garden Earthly Delights Prado Bosch" },
  { name: "rokeby-venus-velazquez.jpg", search: "Rokeby Venus Velázquez" },
  { name: "spinners-velazquez.jpg", search: "Fable Arachne Spinners Velázquez" },
  { name: "water-seller-velazquez.jpg", search: "Water Seller Seville Velázquez" },
  { name: "third-may-detail-goya.jpg", search: "Third May 1808 Goya execution" },
  { name: "saturn-devouring-goya.jpg", search: "Saturn Devouring Son Goya" },
  { name: "sleep-reason-goya.jpg", search: "Sleep Reason Produces Monsters Goya" },
  { name: "burial-orgaz-el-greco.jpg", search: "Burial Count Orgaz El Greco" },
  { name: "view-toledo-el-greco.jpg", search: "View Toledo El Greco" },
  { name: "opening-fifth-seal-el-greco.jpg", search: "Opening Fifth Seal El Greco" },
  { name: "immaculate-conception-murillo.jpg", search: "Immaculate Conception Murillo" },
  { name: "boy-dog-murillo.jpg", search: "Boy Dog Murillo" },

  // ─── French Neoclassicism & Academic ───────────────────────────────────────
  { name: "oath-horatii-david.jpg", search: "Oath Horatii Jacques-Louis David" },
  { name: "death-marat-david.jpg", search: "Death Marat Jacques-Louis David" },
  { name: "napoleon-crossing-alps-david.jpg", search: "Napoleon Crossing Alps David" },
  { name: "coronation-napoleon-david.jpg", search: "Coronation Napoleon David" },
  { name: "intervention-sabine-david.jpg", search: "Intervention Sabine Women David" },
  { name: "grande-odalisque-ingres.jpg", search: "Grande Odalisque Ingres" },
  { name: "apotheosis-homer-ingres.jpg", search: "Apotheosis Homer Ingres" },
  { name: "birth-venus-cabanel.jpg", search: "Birth Venus Alexandre Cabanel" },
  { name: "romans-decadence-couture.jpg", search: "Romans Decadence Thomas Couture" },
  { name: "nymph-scorpion-gerome.jpg", search: "Pollice Verso Jean-Léon Gérôme" },
  { name: "snake-charmer-gerome.jpg", search: "Snake Charmer Gérôme" },

  // ─── Romanticism (additional) ──────────────────────────────────────────────
  { name: "liberty-leading-delacroix2.jpg", search: "Liberty Leading People Delacroix" },
  { name: "death-sardanapalus-delacroix.jpg", search: "Death Sardanapalus Delacroix" },
  { name: "women-algiers-delacroix.jpg", search: "Women Algiers Delacroix" },
  { name: "massacre-chios-delacroix.jpg", search: "Massacre Chios Delacroix" },
  { name: "dante-barque-delacroix.jpg", search: "Dante Barque Delacroix" },
  { name: "raft-medusa-gericault.jpg", search: "Raft Medusa Géricault" },
  { name: "officer-chasseurs-gericault.jpg", search: "Officer Chasseurs Géricault" },
  { name: "wanderer-sea-fog-friedrich.jpg", search: "Wanderer Sea Fog Friedrich" },
  { name: "chalk-cliffs-rugen-friedrich.jpg", search: "Chalk Cliffs Rügen Friedrich" },
  { name: "abbey-oakwood-friedrich.jpg", search: "Abbey Oakwood Friedrich" },
  { name: "sea-ice-friedrich.jpg", search: "Sea Ice Friedrich painting" },
  { name: "stages-life-friedrich.jpg", search: "Stages Life Caspar David Friedrich" },

  // ─── Realism & Naturalism (additional) ─────────────────────────────────────
  { name: "burial-ornans-courbet.jpg", search: "Burial Ornans Gustave Courbet" },
  { name: "origin-world-courbet.jpg", search: "Origin World Courbet" },
  { name: "desperate-man-courbet.jpg", search: "Desperate Man Courbet self portrait" },
  { name: "gleaners-millet.jpg", search: "Gleaners Jean-François Millet" },
  { name: "angelus-millet.jpg", search: "Angelus Jean-François Millet" },
  { name: "man-hoe-millet.jpg", search: "Man Hoe Millet painting" },
  { name: "olympia-manet.jpg", search: "Olympia Édouard Manet" },
  { name: "luncheon-grass-manet.jpg", search: "Luncheon Grass Manet Déjeuner" },
  { name: "bar-folies-bergere-manet.jpg", search: "Bar Folies-Bergère Manet" },

  // ─── Impressionism (additional) ────────────────────────────────────────────
  { name: "bal-moulin-galette-renoir.jpg", search: "Bal Moulin Galette Renoir" },
  { name: "luncheon-boating-renoir.jpg", search: "Luncheon Boating Party Renoir" },
  { name: "dance-bougival-renoir.jpg", search: "Dance Bougival Renoir" },
  { name: "large-bathers-renoir.jpg", search: "Large Bathers Renoir" },
  { name: "rouen-cathedral-monet.jpg", search: "Rouen Cathedral Monet facade" },
  { name: "poppies-monet.jpg", search: "Poppies Argenteuil Monet" },
  { name: "japanese-bridge-monet.jpg", search: "Japanese Bridge Monet water garden" },
  { name: "woman-parasol-monet.jpg", search: "Woman Parasol Monet" },
  { name: "impression-sunrise-monet.jpg", search: "Impression Sunrise Monet" },
  { name: "absinthe-degas.jpg", search: "Absinthe Edgar Degas" },
  { name: "star-dancer-degas.jpg", search: "Star Dancer Stage Edgar Degas" },
  { name: "mary-cassatt-loge.jpg", search: "Loge Mary Cassatt" },
  { name: "child-bath-cassatt.jpg", search: "Child Bath Mary Cassatt" },
  { name: "boating-party-cassatt.jpg", search: "Boating Party Mary Cassatt" },
  { name: "gustave-caillebotte-floor.jpg", search: "Floor Scrapers Caillebotte" },
  { name: "paris-rainy-day-caillebotte.jpg", search: "Paris Street Rainy Day Caillebotte" },
  { name: "moulin-rouge-toulouse.jpg", search: "Moulin Rouge La Goulue Toulouse-Lautrec" },
  { name: "at-moulin-rouge-toulouse.jpg", search: "At Moulin Rouge Toulouse-Lautrec painting" },

  // ─── Post-Impressionism (additional) ───────────────────────────────────────
  { name: "mont-sainte-victoire-cezanne.jpg", search: "Mont Sainte-Victoire Cézanne" },
  { name: "large-bathers-cezanne.jpg", search: "Large Bathers Cézanne" },
  { name: "bedroom-arles-van-gogh.jpg", search: "Bedroom Arles Van Gogh" },
  { name: "cafe-terrace-night-van-gogh.jpg", search: "Café Terrace Night Van Gogh" },
  { name: "sunflowers-van-gogh.jpg", search: "Sunflowers Van Gogh" },
  { name: "irises-van-gogh.jpg", search: "Irises Van Gogh" },
  { name: "wheatfield-crows-van-gogh.jpg", search: "Wheatfield Crows Van Gogh" },
  { name: "self-portrait-bandaged-ear-van-gogh.jpg", search: "Self Portrait Bandaged Ear Van Gogh" },
  { name: "potato-eaters-van-gogh.jpg", search: "Potato Eaters Van Gogh" },
  { name: "almond-blossom-van-gogh.jpg", search: "Almond Blossom Van Gogh" },
  { name: "night-cafe-van-gogh.jpg", search: "Night Café Van Gogh interior" },
  { name: "where-come-from-gauguin.jpg", search: "Where Do We Come From Gauguin" },
  { name: "vision-after-sermon-gauguin.jpg", search: "Vision After Sermon Gauguin" },
  { name: "spirit-dead-watching-gauguin.jpg", search: "Spirit Dead Watching Gauguin" },
  { name: "channel-gravelines-seurat.jpg", search: "Channel Gravelines Seurat" },

  // ─── Symbolism & Art Nouveau (additional) ──────────────────────────────────
  { name: "kiss-klimt.jpg", search: "Kiss Gustav Klimt" },
  { name: "portrait-adele-klimt.jpg", search: "Portrait Adele Bloch-Bauer Klimt" },
  { name: "tree-life-klimt.jpg", search: "Tree Life Klimt Stoclet" },
  { name: "hope-ii-klimt.jpg", search: "Hope II Gustav Klimt" },
  { name: "scream-munch2.jpg", search: "Scream Edvard Munch 1893" },
  { name: "anxiety-munch.jpg", search: "Anxiety Edvard Munch painting" },
  { name: "death-maiden-schiele.jpg", search: "Death Maiden Egon Schiele" },
  { name: "family-schiele.jpg", search: "Family Egon Schiele" },
  { name: "cyclops-redon.jpg", search: "Cyclops Odilon Redon" },
  { name: "jupiter-thetis-moreau.jpg", search: "Jupiter Thetis Gustave Moreau" },
  { name: "salome-moreau.jpg", search: "Salome Dancing Gustave Moreau" },

  // ─── Cubism & Fauvism (additional) ─────────────────────────────────────────
  { name: "demoiselles-avignon-picasso.jpg", search: "Demoiselles Avignon Picasso" },
  { name: "seated-woman-picasso.jpg", search: "Seated Woman Picasso 1937" },
  { name: "woman-hat-matisse.jpg", search: "Woman Hat Henri Matisse" },
  { name: "snail-matisse.jpg", search: "Snail Henri Matisse" },
  { name: "portuguese-braque.jpg", search: "Portuguese Georges Braque" },
  { name: "man-guitar-braque.jpg", search: "Man Guitar Georges Braque" },
  { name: "eiffel-tower-delaunay.jpg", search: "Eiffel Tower Robert Delaunay" },
  { name: "circular-forms-delaunay.jpg", search: "Circular Forms Robert Delaunay" },
  { name: "sleeping-gypsy-rousseau.jpg", search: "Sleeping Gypsy Henri Rousseau" },
  { name: "dream-rousseau.jpg", search: "Dream Henri Rousseau" },

  // ─── Surrealism (additional) ───────────────────────────────────────────────
  { name: "persistence-memory-dali.jpg", search: "Persistence Memory Salvador Dalí" },
  { name: "burning-giraffes-dali.jpg", search: "Burning Giraffes Dalí" },
  { name: "treachery-images-magritte.jpg", search: "Treachery Images Magritte pipe" },
  { name: "empire-light-magritte.jpg", search: "Empire Light Magritte" },
  { name: "i-and-village-chagall.jpg", search: "I and Village Marc Chagall" },
  { name: "over-town-chagall.jpg", search: "Over Town Marc Chagall" },
  { name: "harlequin-carnival-miro.jpg", search: "Harlequin Carnival Joan Miró" },
  { name: "farm-miro.jpg", search: "Farm Joan Miró" },
  { name: "dutch-interior-miro.jpg", search: "Dutch Interior Miró" },
  { name: "robing-bride-ernst.jpg", search: "Robing Bride Max Ernst" },

  // ─── Abstract Expressionism & Modern (additional) ──────────────────────────
  { name: "broadway-boogie-mondrian.jpg", search: "Broadway Boogie Woogie Mondrian" },
  { name: "number-1-pollock.jpg", search: "Number 1A Lavender Mist Pollock" },
  { name: "no-61-rust-blue-rothko.jpg", search: "No 61 Rust Blue Mark Rothko" },
  { name: "no-14-rothko.jpg", search: "No 14 White Greens Blue Mark Rothko" },
  { name: "vir-heroicus-newman.jpg", search: "Vir Heroicus Sublimis Barnett Newman" },
  { name: "untitled-1960-kline.jpg", search: "Painting Number 2 Franz Kline" },
  { name: "target-four-faces-johns.jpg", search: "Target Four Faces Jasper Johns" },
  { name: "erased-de-kooning-rauschenberg.jpg", search: "Erased de Kooning Rauschenberg" },
  { name: "monogram-rauschenberg.jpg", search: "Monogram Robert Rauschenberg" },

  // ─── Pop Art & Contemporary (additional) ───────────────────────────────────
  { name: "campbell-soup-warhol.jpg", search: "Campbell Soup Cans Andy Warhol" },
  { name: "shot-marilyn-warhol.jpg", search: "Shot Sage Blue Marilyn Warhol" },
  { name: "pool-two-figures-hockney.jpg", search: "Portrait Artist Pool Two Figures Hockney" },
  { name: "mr-mrs-clark-percy-hockney.jpg", search: "Mr Mrs Clark Percy Hockney" },
  { name: "study-after-velazquez-bacon.jpg", search: "Study After Velázquez Pope Innocent Bacon" },
  { name: "figure-with-meat-bacon.jpg", search: "Figure Meat Francis Bacon" },
  { name: "reflection-two-children-freud.jpg", search: "Large Interior Paddington Lucian Freud" },

  // ─── American Art (additional) ─────────────────────────────────────────────
  { name: "office-at-night-hopper.jpg", search: "Office Night Edward Hopper" },
  { name: "wind-from-sea-wyeth.jpg", search: "Wind Sea Andrew Wyeth" },
  { name: "american-gothic-wood.jpg", search: "American Gothic Grant Wood" },
  { name: "washington-crossing-leutze.jpg", search: "Washington Crossing Delaware Leutze" },
  { name: "triple-self-portrait-rockwell.jpg", search: "Triple Self Portrait Norman Rockwell" },
  { name: "problem-we-all-live-rockwell.jpg", search: "Problem We All Live With Norman Rockwell" },
  { name: "snap-whip-homer.jpg", search: "Snap Whip Winslow Homer" },

  // ─── Italian Renaissance (additional) ──────────────────────────────────────
  { name: "expulsion-eden-masaccio.jpg", search: "Expulsion Garden Eden Masaccio" },
  { name: "resurrection-piero-della-francesca.jpg", search: "Resurrection Piero della Francesca Sansepolcro" },
  { name: "ideal-city-urbino.jpg", search: "Ideal City Urbino painting" },
  { name: "madonna-goldfinch-raphael.jpg", search: "Madonna Goldfinch Raphael" },
  { name: "school-of-athens-raphael.jpg", search: "School Athens Raphael Vatican" },
  { name: "madonna-meadow-raphael.jpg", search: "Madonna Meadow Raphael" },
  { name: "creation-adam-michelangelo.jpg", search: "Creation Adam Michelangelo Sistine" },
  { name: "deluge-michelangelo.jpg", search: "Deluge Michelangelo Sistine ceiling" },
  { name: "bacchus-ariadne-titian.jpg", search: "Bacchus Ariadne Titian" },
  { name: "venus-urbino-titian.jpg", search: "Venus Urbino Titian" },
  { name: "man-red-turban-van-eyck.jpg", search: "Man Red Turban Van Eyck self portrait" },
  { name: "madonna-chancellor-rolin-van-eyck.jpg", search: "Madonna Chancellor Rolin Van Eyck" },

  // ─── Baroque (additional) ──────────────────────────────────────────────────
  { name: "judith-holofernes-gentileschi.jpg", search: "Judith Slaying Holofernes Artemisia Gentileschi" },
  { name: "self-portrait-gentileschi.jpg", search: "Self Portrait Allegory Painting Artemisia Gentileschi" },
  { name: "calling-st-matthew-caravaggio.jpg", search: "Calling Saint Matthew Caravaggio" },
  { name: "supper-emmaus-caravaggio.jpg", search: "Supper Emmaus Caravaggio London" },
  { name: "entombment-christ-caravaggio.jpg", search: "Entombment Christ Caravaggio" },
  { name: "garden-love-rubens.jpg", search: "Garden Love Peter Paul Rubens" },
  { name: "judgment-paris-rubens.jpg", search: "Judgment Paris Rubens" },
  { name: "girl-pearl-earring-vermeer.jpg", search: "Girl Pearl Earring Vermeer" },
  { name: "milkmaid-vermeer.jpg", search: "Milkmaid Vermeer" },

  // ─── 18th Century & Rococo (additional) ────────────────────────────────────
  { name: "swing-fragonard.jpg", search: "Swing Jean-Honoré Fragonard" },
  { name: "pierrot-watteau.jpg", search: "Pierrot Gilles Watteau" },
  { name: "fete-galante-watteau.jpg", search: "Fête Galante Watteau" },
  { name: "girl-dead-bird-greuze.jpg", search: "Girl Dead Bird Jean-Baptiste Greuze" },
  { name: "young-woman-drawing-chardin.jpg", search: "Young Woman Drawing Chardin" },
  { name: "boy-spinning-top-chardin.jpg", search: "Boy Spinning Top Chardin" },
  { name: "ray-chardin.jpg", search: "Ray Jean Siméon Chardin" },
  { name: "nightmare-fuseli.jpg", search: "Nightmare Henry Fuseli" },
  { name: "experiment-air-pump-wright.jpg", search: "Experiment Bird Air Pump Wright Derby" },
  { name: "capriccio-canaletto.jpg", search: "Grand Canal Canaletto Venice painting" },
  { name: "venetian-festival-guardi.jpg", search: "Venice Festival Guardi painting" },
  { name: "tiepolo-ceiling.jpg", search: "Allegory Planets Continents Tiepolo" },

  // ─── 19th Century Academic & Salon ─────────────────────────────────────────
  { name: "death-socrates-david.jpg", search: "Death Socrates Jacques-Louis David" },
  { name: "madame-recamier-david.jpg", search: "Madame Récamier Jacques-Louis David" },
  { name: "romantic-landscape-cole.jpg", search: "Oxbow Thomas Cole painting" },
  { name: "rocky-mountain-bierstadt.jpg", search: "Rocky Mountain Landers Peak Bierstadt" },
  { name: "twilight-wilderness-church.jpg", search: "Twilight Wilderness Frederic Church" },
  { name: "fur-traders-bingham.jpg", search: "Fur Traders Descending Missouri Bingham" },
  { name: "peaceable-kingdom-hicks.jpg", search: "Peaceable Kingdom Edward Hicks" },
  { name: "watson-shark-copley.jpg", search: "Watson Shark John Singleton Copley" },
  { name: "pygmalion-galatea-gerome.jpg", search: "Pygmalion Galatea Jean-Léon Gérôme" },

  // ─── Nabis, Fauves & Early Modern (additional) ────────────────────────────
  { name: "talisman-serusier.jpg", search: "Talisman Paul Sérusier" },
  { name: "women-garden-bonnard.jpg", search: "Women Garden Pierre Bonnard" },
  { name: "dining-room-country-bonnard.jpg", search: "Dining Room Country Bonnard" },
  { name: "muses-maurice-denis.jpg", search: "Muses Maurice Denis" },
  { name: "luxe-calme-matisse.jpg", search: "Luxe Calme Volupté Matisse" },
  { name: "derain-london-bridge.jpg", search: "London Bridge André Derain" },
  { name: "derain-charing-cross.jpg", search: "Charing Cross Bridge André Derain" },
  { name: "vlaminck-chatou.jpg", search: "Houses Chatou Maurice de Vlaminck" },
  { name: "dufy-regatta.jpg", search: "Regatta Cowes Raoul Dufy" },
  { name: "rouault-holy-face.jpg", search: "Holy Face Georges Rouault" },
  { name: "modigliani-reclining-nude.jpg", search: "Reclining Nude Amedeo Modigliani" },
  { name: "modigliani-jeanne.jpg", search: "Jeanne Hébuterne Modigliani portrait" },
  { name: "nude-descending-duchamp.jpg", search: "Nude Descending Staircase Marcel Duchamp" },
  { name: "large-glass-duchamp.jpg", search: "Bride Stripped Bare Bachelors Duchamp" },

  // ─── German Expressionism & Die Brücke ─────────────────────────────────────
  { name: "marcella-kirchner.jpg", search: "Marcella Ernst Ludwig Kirchner" },
  { name: "blue-horse-marc.jpg", search: "Large Blue Horses Franz Marc" },
  { name: "fate-animals-marc.jpg", search: "Fate Animals Franz Marc" },
  { name: "fable-klee.jpg", search: "Ad Parnassum Paul Klee" },
  { name: "nolde-prophet.jpg", search: "Prophet Emil Nolde" },
  { name: "nolde-dance-golden-calf.jpg", search: "Dance Golden Calf Emil Nolde" },
  { name: "beckmann-departure.jpg", search: "Departure Max Beckmann triptych" },
  { name: "beckmann-night.jpg", search: "Night Max Beckmann painting" },
  { name: "dix-war-triptych.jpg", search: "War Otto Dix triptych" },
  { name: "metropolis-grosz.jpg", search: "Metropolis George Grosz" },

  // ─── Constructivism & De Stijl (additional) ────────────────────────────────
  { name: "tatlin-tower-model.jpg", search: "Monument Third International Tatlin" },
  { name: "lissitzky-beat-whites.jpg", search: "Beat Whites Red Wedge Lissitzky" },
  { name: "popova-painterly.jpg", search: "Painterly Architectonic Liubov Popova" },
  { name: "vantongerloo-composition.jpg", search: "Composition Georges Vantongerloo" },
  { name: "theo-van-doesburg-composition.jpg", search: "Counter Composition Theo van Doesburg" },

  // ─── Mid-Century & Post-War ────────────────────────────────────────────────
  { name: "still-1957-painting.jpg", search: "1957-D No 1 Clyfford Still" },
  { name: "reinhardt-abstract-painting.jpg", search: "Abstract Painting Ad Reinhardt black" },
  { name: "twombly-blackboard.jpg", search: "Untitled Blackboard Cy Twombly" },
  { name: "diebenkorn-ocean-park.jpg", search: "Ocean Park Richard Diebenkorn" },
  { name: "agnes-martin-untitled.jpg", search: "Untitled Agnes Martin grid" },
  { name: "stella-harran.jpg", search: "Harran II Frank Stella" },
  { name: "louis-unfurled.jpg", search: "Alpha Phi Morris Louis" },
  { name: "riley-movement-squares.jpg", search: "Movement Squares Bridget Riley" },
  { name: "vasarely-vega.jpg", search: "Vega 200 Victor Vasarely" },
  { name: "albers-homage-square.jpg", search: "Homage Square Josef Albers" },

  // ─── Additional Notable Works ──────────────────────────────────────────────
  { name: "la-promenade-renoir.jpg", search: "La Promenade Renoir" },
  { name: "jane-avril-toulouse.jpg", search: "Jane Avril Toulouse-Lautrec poster" },
  { name: "salon-rue-moulins-toulouse.jpg", search: "Salon Rue des Moulins Toulouse-Lautrec" },
  { name: "woman-iron-degas.jpg", search: "Woman Ironing Degas" },
  { name: "pont-neuf-renoir.jpg", search: "Pont Neuf Pierre-Auguste Renoir" },
  { name: "two-sisters-terrace-renoir.jpg", search: "Two Sisters Terrace Renoir" },
  { name: "water-lilies-morning-monet.jpg", search: "Water Lilies Morning Monet Orangerie" },
  { name: "manneporte-monet.jpg", search: "Manneporte Monet Etretat" },
  { name: "houses-parliament-sunset-monet.jpg", search: "Houses Parliament Sunset Monet" },
  { name: "self-portrait-straw-hat-van-gogh.jpg", search: "Self Portrait Straw Hat Van Gogh" },
  { name: "red-vineyard-van-gogh.jpg", search: "Red Vineyard Van Gogh" },
  { name: "church-auvers-van-gogh.jpg", search: "Church Auvers Van Gogh" },
  { name: "starry-night-rhone-van-gogh.jpg", search: "Starry Night Over Rhône Van Gogh" },
  { name: "blue-nude-matisse.jpg", search: "Blue Nude Souvenir Biskra Matisse" },
  { name: "goldfish-matisse.jpg", search: "Goldfish Henri Matisse" },
  { name: "houses-estaque-cezanne.jpg", search: "Houses Estaque Cézanne" },
  { name: "lady-ermine-leonardo.jpg", search: "Lady Ermine Leonardo da Vinci" },
  { name: "virgin-rocks-leonardo.jpg", search: "Virgin Rocks Leonardo da Vinci" },
  { name: "terrace-sainte-adresse-monet.jpg", search: "Terrace Sainte-Adresse Monet" },
  { name: "olympia-detail-manet.jpg", search: "Olympia Manet detail" },
  { name: "st-george-dragon-raphael.jpg", search: "Saint George Dragon Raphael" },
  { name: "madonna-sistine-raphael.jpg", search: "Sistine Madonna Raphael" },
  { name: "marriage-virgin-raphael.jpg", search: "Marriage Virgin Raphael Sposalizio" },
];
